# Generated by Django 4.2.20 on 2025-07-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showcase', '0025_remove_battle_participants_remove_battle_robots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Account Profile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('showcase.profiledetails',),
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
            ],
            options={
                'verbose_name': 'Player Inventory',
                'verbose_name_plural': 'Player Inventories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('showcase.inventory',),
        ),
    ]
