# Generated by Django 5.1.6 on 2025-04-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Account Profile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('showcase.profiledetails',),
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
            ],
            options={
                'verbose_name': 'Player Inventory',
                'verbose_name_plural': 'Player Inventories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('showcase.inventory',),
        ),
    ]
