# Generated by Django 4.1.10 on 2024-03-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeshippinglabel',
            name='responding_trade_offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showcase.respondingtradeoffer'),
        ),
    ]
