# Generated by Django 4.1.10 on 2024-08-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commerceexchange',
            name='prize',
        ),
        migrations.AddField(
            model_name='commerceexchange',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commerceexchange',
            name='prizes',
            field=models.ManyToManyField(to='showcase.exchangeprize'),
        ),
        migrations.AddField(
            model_name='commerceexchange',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
