# Generated by Django 5.1.6 on 2025-04-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcoderedemption',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userclickable',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battlegame',
            name='outcome_created',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='value',
            field=models.IntegerField(default=1000),
        ),
    ]
