# Generated by Django 4.1.10 on 2025-03-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleparticipant',
            name='robot',
        ),
    ]
