# Generated by Django 4.2.20 on 2025-05-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubyDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timeframe', models.IntegerField(default=3600)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Epic'), ('M', 'Mythical'), ('T', 'Transcendent'), ('P', 'Primordial'), ('L', 'Legendary'), ('U', 'Ultimate'), ('F', 'Final')], max_length=1)),
                ('opentime', models.IntegerField(default=300)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
            ],
            options={
                'verbose_name': 'Ruby Drop',
                'verbose_name_plural': 'Ruby Drops',
            },
        ),
        migrations.CreateModel(
            name='RubyDropInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Epic'), ('M', 'Mythical'), ('T', 'Transcendent'), ('P', 'Primordial'), ('L', 'Legendary'), ('U', 'Ultimate'), ('F', 'Final')], max_length=1)),
                ('opentime', models.IntegerField(default=300)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
                ('rubydrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.rubydrop')),
            ],
            options={
                'verbose_name': 'Ruby Drop',
                'verbose_name_plural': 'Ruby Drops',
            },
        ),
    ]
