# Generated by Django 3.1.5 on 2021-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='description',
            field=models.TextField(help_text='Post your profile here.'),
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='name',
            field=models.CharField(help_text='Your name goes here.', max_length=100),
        ),
    ]
