# Generated by Django 4.1.2 on 2023-06-27 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'About Background Image',
                'verbose_name_plural': 'About Background Images',
            },
        ),
        migrations.CreateModel(
            name='AccountBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Account Background Image',
                'verbose_name_plural': 'Account Background Images',
            },
        ),
        migrations.CreateModel(
            name='AddonsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Addons Background Image',
                'verbose_name_plural': 'Addons Background Images',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1000)),
                ('default', models.BooleanField(default=False)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active address?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AdminPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(max_length=30, verbose_name='Administration pages')),
                ('hyperlink', models.CharField(max_length=100, verbose_name='Page hyperlinks')),
                ('opennew', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Please note all Administration Interface Pages should open in a new tab.', verbose_name='Open In New Tab?')),
                ('section', models.IntegerField(help_text='Position of the page link.', verbose_name='position')),
                ('page_name', models.TextField(blank='True', null='True', verbose_name='Page Name')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active page?')),
            ],
            options={
                'verbose_name_plural': 'Administrative Pages',
            },
        ),
        migrations.CreateModel(
            name='AdminRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=30, verbose_name='Administration roles')),
                ('role_description', models.TextField(blank='True', null='True', verbose_name='Role Overview')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this role currently active?')),
            ],
            options={
                'verbose_name_plural': 'Administrative Roles',
            },
        ),
        migrations.CreateModel(
            name='AdminTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30, verbose_name='Administration tasks')),
                ('hyperlink', models.CharField(blank='True', help_text='Only add if necessary', max_length=100, null='True', verbose_name='Task hyperlink')),
                ('opennew', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Please note all Administration Interface Pages should open in a new tab.', verbose_name='Open In New Tab?')),
                ('section', models.IntegerField(help_text='Position of the page link.', verbose_name='position')),
                ('page_name', models.TextField(blank='True', null='True', verbose_name='Page Name')),
                ('image', models.ImageField(upload_to='', verbose_name='Task image')),
                ('alternate', models.TextField(verbose_name='Alternate text')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this task currently active?')),
            ],
            options={
                'verbose_name_plural': 'Administrative Tasks',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisementtitle', models.CharField(help_text='Advertisement title.', max_length=100, verbose_name='advertisement title')),
                ('advertisement', models.ImageField(height_field='advertisement_width', help_text='Image of the advertisement.', upload_to='images/', width_field='advertisement_length')),
                ('advertisement_length', models.PositiveIntegerField(blank=True, default='100', help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='advertisement length')),
                ('advertisement_width', models.PositiveIntegerField(blank=True, default='100', help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='advertisement width')),
                ('length_for_resize', models.PositiveIntegerField(default=40, verbose_name='Resized Length')),
                ('width_for_resize', models.PositiveIntegerField(default=600, verbose_name='Resized Width')),
                ('advertisement_position', models.IntegerField(help_text='Positioning of the advertisement.', verbose_name='Position')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('xposition', models.IntegerField(help_text='x-position.', verbose_name='x-position')),
                ('yposition', models.IntegerField(help_text='x-position.', verbose_name='y-position')),
                ('relevance', models.TextField(help_text='Relevance of advertisement')),
                ('type', models.CharField(help_text='Type of product.', max_length=200)),
                ('advertisement_hyperlink', models.TextField(verbose_name='Hyperlink')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Advertisement Base',
                'verbose_name_plural': 'Advertisement Base',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('page', models.TextField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Background Image',
                'verbose_name_plural': 'Background Images',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImageBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundtitle', models.TextField(verbose_name='Background Title')),
                ('cover', models.ImageField(upload_to='images/')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('url', models.URLField(verbose_name='Page URL')),
                ('position', models.IntegerField(verbose_name='Image Position')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Background Image Base',
                'verbose_name_plural': 'Background Image Base',
            },
        ),
        migrations.CreateModel(
            name='BanAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here.', max_length=100)),
                ('Rule_broken', models.CharField(help_text='Tell us the numbers of the rule(s) you broke. Refer to our rules page to see the rules and their corresponding numbers.', max_length=200)),
                ('Why_I_should_have_my_ban_revoked', models.TextField(help_text='Tell us why we should unban you, and tell us you can do to fix your mistake. If you think your punishment is a mistake, tell us why.', verbose_name='Why I should have my ban revoked.')),
                ('Additional_comments', models.TextField(help_text='Put any additional evidence or comments you may have here.')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Ban Appeal',
                'verbose_name_plural': 'Ban Appeals',
            },
        ),
        migrations.CreateModel(
            name='BanAppealBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Ban Appliciations Background Image',
                'verbose_name_plural': 'Ban Applications Background Images',
            },
        ),
        migrations.CreateModel(
            name='BaseCopyrightTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.TextField(help_text='Copyright And Year', verbose_name='Copyright Field')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('hyperlink', models.TextField(verbose_name='Hyperlink')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Base Text Field Copyright',
                'verbose_name_plural': 'Base Text Field Copyright',
            },
        ),
        migrations.CreateModel(
            name='BilletBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Billet Background Image',
                'verbose_name_plural': 'Billet Background Images',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on: ')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='post_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='post dislikes')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='post likes')),
            ],
            options={
                'verbose_name': 'Blog Entry',
                'verbose_name_plural': 'Blog Entries',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='BlogBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('cover', models.ImageField(upload_to='images/', verbose_name='Cover')),
            ],
            options={
                'verbose_name': 'Blog Background Image',
                'verbose_name_plural': 'Blog Background Images',
            },
        ),
        migrations.CreateModel(
            name='BusinessMailingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Recipient of your message.')),
                ('inquiry', models.CharField(help_text='Subject of your message.', max_length=100)),
                ('message', models.TextField(help_text='Your message goes here.')),
            ],
            options={
                'verbose_name': 'Business Mailing Message',
                'verbose_name_plural': 'Business Mailing Messages',
            },
        ),
        migrations.CreateModel(
            name='BusinessMessageBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Business Message Background Image',
                'verbose_name_plural': 'Business Message Background Images',
            },
        ),
        migrations.CreateModel(
            name='ChangePasswordBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Change Password Background Image',
                'verbose_name_plural': 'Change Password Background Images',
            },
        ),
        migrations.CreateModel(
            name='ChatBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Chat Background Image',
                'verbose_name_plural': 'Chat Background Images',
            },
        ),
        migrations.CreateModel(
            name='CheckoutBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Checkout Background Image',
                'verbose_name_plural': 'Checkout Background Images',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CommitmentBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Commitment Background Image',
                'verbose_name_plural': 'Commitment Background Images',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Recipient of your message.')),
                ('inquiry', models.CharField(help_text='Subject of your message.', max_length=100)),
                ('message', models.TextField(help_text='Your message goes here.')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='ContactBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Contact Background Image',
                'verbose_name_plural': 'Contact Background Images',
            },
        ),
        migrations.CreateModel(
            name='ContentBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Content Background Image',
                'verbose_name_plural': 'Content Background Images',
            },
        ),
        migrations.CreateModel(
            name='ContributorBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Contributors Background Image',
                'verbose_name_plural': 'Contributors Background Images',
            },
        ),
        migrations.CreateModel(
            name='ConvertBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Convert Background Image',
                'verbose_name_plural': 'Convert Background Images',
            },
        ),
        migrations.CreateModel(
            name='CostBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Cost Background Image',
                'verbose_name_plural': 'Cost Background Images',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('percentDollars', models.BooleanField(default=False)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active coupon?')),
            ],
        ),
        migrations.CreateModel(
            name='DonateIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Donation Icon',
                'verbose_name_plural': 'Donation Icons',
            },
        ),
        migrations.CreateModel(
            name='DonorBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Donors Background Image',
                'verbose_name_plural': 'Donors Background Images',
            },
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here. If you wish to stay anonymous, put "Anonymous".', max_length=100)),
                ('category', models.CharField(help_text='Please let us know what type of issue you are dealing with.', max_length=200)),
                ('issue', models.TextField(help_text='Describe your issue in detail. We will try to get back to you as soon as possible.')),
                ('Additional_comments', models.TextField(help_text='Put any additional comments you may have here.', verbose_name='additional comments')),
                ('image', models.ImageField(help_text='Please attach a screenshot of your issue.', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Customer Support',
                'verbose_name_plural': 'Customer Support',
            },
        ),
        migrations.CreateModel(
            name='EBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Ecommerce Background Image',
                'verbose_name_plural': 'Ecommerce Background Images',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name goes here.', max_length=100)),
                ('category', models.CharField(help_text='Please let us know what type of event this is (tournament, stage night, etc).', max_length=200)),
                ('description', models.TextField(help_text='Give a brief description of the event.')),
                ('date_and_time', models.DateTimeField(null=True, verbose_name='time and date')),
                ('image', models.FileField(help_text='Please provide a cover image for your profile.', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
        ),
        migrations.CreateModel(
            name='EventBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Event Background Image',
                'verbose_name_plural': 'Event Background Images',
            },
        ),
        migrations.CreateModel(
            name='FaqBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'FAQ Background Image',
                'verbose_name_plural': 'FAQ Background Images',
            },
        ),
        migrations.CreateModel(
            name='FaviconBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicontitle', models.TextField(verbose_name='Favicon Title')),
                ('faviconcover', models.ImageField(upload_to='images/', verbose_name='Favicon')),
                ('favicon_length', models.PositiveIntegerField(blank=True, default='100', help_text='Original length of the favicon (use for original ratio).', null=True, verbose_name='advertisement length')),
                ('favicon_width', models.PositiveIntegerField(blank=True, default='100', help_text='Original width of the favicon (use for original ratio).', null=True, verbose_name='advertisement width')),
                ('length_for_resize', models.PositiveIntegerField(default=40, verbose_name='Resized Length')),
                ('width_for_resize', models.PositiveIntegerField(default=600, verbose_name='Resized Width')),
                ('faviconpage', models.TextField(verbose_name='Page Name')),
                ('faviconurl', models.URLField(verbose_name='Page URL')),
                ('faviconlink', models.TextField(verbose_name='Favicon Link')),
                ('faviconsizes', models.TextField(help_text='example: 180x180', verbose_name='Favicon Sizes')),
                ('faviconrelationship', models.TextField(help_text='example: icon', verbose_name='Favicon Relationship')),
                ('favicontype', models.TextField(help_text='example: ico', verbose_name='Favicon Type')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicons',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name goes here.', max_length=100)),
                ('category', models.CharField(help_text='Choose a category you want your idea to affect (server layout, event idea, etc).', max_length=100)),
                ('description', models.TextField(help_text='Please share any ideas you may have.')),
                ('image', models.ImageField(help_text='Attach an image for your idea (scales to your picture`s dimensions).', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
            },
        ),
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouseltitle', models.CharField(help_text='Title of the image.', max_length=100, verbose_name='title')),
                ('carouselcaption', models.TextField(help_text='Caption for the image.', verbose_name='caption')),
                ('carouselimage', models.ImageField(help_text='Upload an image for the carousel.)', upload_to='images/', verbose_name='image')),
                ('carouselposition', models.IntegerField(help_text='Positioning of the image within the carousel.', verbose_name='position')),
                ('carouseltotal', models.IntegerField(help_text='Total number of images within the carousel.', verbose_name='total images')),
                ('carouselpage', models.TextField(verbose_name='Page Name')),
                ('hyperlink', models.TextField(verbose_name='Hyperlink')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Image Carousel Idea',
                'verbose_name_plural': 'Image Carousel Posts',
            },
        ),
        migrations.CreateModel(
            name='InformationBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Information Background Image',
                'verbose_name_plural': 'Information Background Images',
            },
        ),
        migrations.CreateModel(
            name='IssueBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Issue Background Image',
                'verbose_name_plural': 'Issue Background Images',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('G', 'Gold'), ('P', 'Platinum'), ('E', 'Emerald'), ('D', 'Diamond')], max_length=2)),
                ('label', models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], max_length=1000)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('hyperlink', models.TextField(blank=True, help_text='Feedbacks will use this hyperlink as a link to this product.', null=True, verbose_name='Hyperlink')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Out of stock?')),
                ('relateditems', models.ManyToManyField(blank=True, to='showcase.item', verbose_name='Related Items:')),
            ],
        ),
        migrations.CreateModel(
            name='LogoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Background Title')),
                ('logocover', models.ImageField(upload_to='images/', verbose_name='Logo')),
                ('hyperlink', models.TextField(verbose_name='Hyperlink')),
                ('section', models.IntegerField(verbose_name='Page Section')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('alternate', models.TextField(verbose_name='Alternate Text')),
                ('logo_length', models.PositiveIntegerField(blank=True, default='100', help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='advertisement length')),
                ('logo_width', models.PositiveIntegerField(blank=True, default='100', help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='advertisement width')),
                ('length_for_resize', models.PositiveIntegerField(default=40, verbose_name='Resized Length')),
                ('width_for_resize', models.PositiveIntegerField(default=600, verbose_name='Resized Width')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='MantenienceBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Mantenience Background Image',
                'verbose_name_plural': 'Mantenience Background Images',
            },
        ),
        migrations.CreateModel(
            name='MegaBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Mega Background Image',
                'verbose_name_plural': 'Mega Background Images',
            },
        ),
        migrations.CreateModel(
            name='MemberHomeBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Member Home Background Image',
                'verbose_name_plural': 'Member Home Background Images',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=1000000)),
                ('room', models.CharField(max_length=1000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.TextField(blank=True, null=True)),
                ('row', models.IntegerField()),
                ('position', models.IntegerField()),
                ('opennew', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Open In New Tab?')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Navigational Bar Dropdown',
                'verbose_name_plural': 'Navigational Bar Dropdowns',
            },
        ),
        migrations.CreateModel(
            name='NavBarHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='This is a header.')),
                ('section', models.TextField(blank=True, help_text='ID Section of page.', max_length=200, null=True)),
                ('row', models.IntegerField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Navigational Bar Header',
                'verbose_name_plural': 'Navigational Bar Headers',
            },
        ),
        migrations.CreateModel(
            name='NewsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'News Background Image',
                'verbose_name_plural': 'News Background Images',
            },
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here. If you wish to stay anonymous, put "Anonymous".', max_length=100)),
                ('category', models.CharField(help_text='Please let us know what form of news this is.', max_length=200)),
                ('description', models.TextField(help_text='Write the news here.')),
                ('image', models.FileField(help_text='Please provide a cover image for the news.', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'News Feed',
                'verbose_name_plural': 'News Feed',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback_url', models.URLField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active order?')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='showcase.address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.coupon')),
                ('itemhistory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.item', verbose_name='Order history')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Order Background Image',
                'verbose_name_plural': 'Order Background Images',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to use corresponding product slug.', max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your server name goes here.', max_length=100)),
                ('catagory', models.CharField(help_text='Pick a catagory you feel your server represents (gaming, community, etc).', max_length=100)),
                ('description', models.TextField(help_text='Describe your server. Tell potential members why they should join.')),
                ('server_invite', models.URLField(help_text='Post your server invite link here.')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your server name goes here.', max_length=100)),
                ('category', models.CharField(help_text='Pick a category you feel your server represents (gaming, community, etc).', max_length=100)),
                ('description', models.TextField(help_text='Describe your server. Tell potential members why they should join.')),
                ('server_invite', models.URLField(help_text='Idea your server invite link here.')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Partner Background Image',
                'verbose_name_plural': 'Partner Background Images',
            },
        ),
        migrations.CreateModel(
            name='Patreon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patreon_username', models.CharField(help_text='The patreon`s username goes here.', max_length=100, verbose_name='Patreon`s Username')),
                ('description', models.TextField(help_text='Description of Patreon`s patreonage.')),
                ('image', models.ImageField(help_text='The patreon`s avatar goes here.', upload_to='')),
            ],
            options={
                'verbose_name': 'Patreon',
                'verbose_name_plural': 'Patreons',
            },
        ),
        migrations.CreateModel(
            name='PatreonBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Patreon Background Image',
                'verbose_name_plural': 'Patreon Background Images',
            },
        ),
        migrations.CreateModel(
            name='PerksBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Perks Background Image',
                'verbose_name_plural': 'Perks Background Images',
            },
        ),
        migrations.CreateModel(
            name='PostBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Idea Background Image',
                'verbose_name_plural': 'Idea Background Images',
            },
        ),
        migrations.CreateModel(
            name='PosteBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Idea Background Image',
                'verbose_name_plural': 'Idea Background Images',
            },
        ),
        migrations.CreateModel(
            name='PriceBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Price Background Image',
                'verbose_name_plural': 'Price Background Images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('description', models.TextField()),
                ('mfg_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('b', 'Bad'), ('a', 'Average'), ('e', 'Excellent')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Product Background Image',
                'verbose_name_plural': 'Product Background Images',
            },
        ),
        migrations.CreateModel(
            name='PunishAppsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Punishment Applications Background Image',
                'verbose_name_plural': 'Punishment Applications Background Images',
            },
        ),
        migrations.CreateModel(
            name='PunishmentAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here.', max_length=100)),
                ('Rule_broken', models.CharField(help_text='Tell us the numbers of the rule(s) you broke. Refer to our rules page to see the rules and their corresponding numbers.', max_length=200, verbose_name='rule broken: ')),
                ('Why_I_should_have_my_punishment_revoked', models.TextField(help_text='Tell us why we should revoke your punishment, and what you can do to fix your mistake. If you think your punishment is a mistake, tell us why.', verbose_name='Why I should have my punishment revoked: ')),
                ('Additional_comments', models.TextField(help_text='Put any additional evidence or comments you may have here.', verbose_name='additional comments ')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Punishment Appeal',
                'verbose_name_plural': 'Punishment Appeals',
            },
        ),
        migrations.CreateModel(
            name='ReasonsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Reasons Background Image',
                'verbose_name_plural': 'Reasons Background Images',
            },
        ),
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here. If you wish to stay anonymous, put "Anonymous".', max_length=100)),
                ('category', models.CharField(help_text='Please let us know what type of issue this is.', max_length=200)),
                ('issue', models.TextField(help_text='Describe the issue in detail. We will try to get to it as soon as possible.')),
                ('Additional_comments', models.TextField(help_text='Put any additional comments you may have here.', verbose_name='additional comments')),
                ('image', models.FileField(help_text='Please put a screenshot of the issue.', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Report Issue',
                'verbose_name_plural': 'Report Issues',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RuleBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Rule Background Image',
                'verbose_name_plural': 'Rule Background Images',
            },
        ),
        migrations.CreateModel(
            name='ServerBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Server Background Image',
                'verbose_name_plural': 'Server Background Images',
            },
        ),
        migrations.CreateModel(
            name='SettingsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Settings Background Image',
                'verbose_name_plural': 'Settings Background Images',
            },
        ),
        migrations.CreateModel(
            name='ShareBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Share Background Image',
                'verbose_name_plural': 'Share Background Images',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Showcase Background Image',
                'verbose_name_plural': 'Showcase Background Images',
            },
        ),
        migrations.CreateModel(
            name='SignupBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Signup Background Image',
                'verbose_name_plural': 'SignupBackground Images',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.TextField(verbose_name='Social Media Platform')),
                ('image', models.ImageField(upload_to='', verbose_name='Social Media Logo')),
                ('image_width', models.PositiveIntegerField(blank=True, default='100', help_text='Width of the image (in percent relative).', null=True, verbose_name='image width')),
                ('image_length', models.PositiveIntegerField(blank=True, default='100', help_text='Length of the image (in percent relative).', null=True, verbose_name='image length')),
                ('width_for_resize', models.PositiveIntegerField(default=600, verbose_name='Resize Width')),
                ('height_for_resize', models.PositiveIntegerField(default=40, verbose_name='Resize Height')),
                ('image_position', models.IntegerField(help_text='Positioning of the image.', verbose_name='Position')),
                ('alternate', models.TextField(verbose_name='Alternate Text')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('hyperlink', models.TextField(verbose_name='Hyperlink')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name & tag go here.', max_length=100)),
                ('overall_time_check', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have been in MC for at least 2 months')),
                ('previous_role_time_check', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have been in MC for at least 1 month')),
                ('meeting_attendance_check', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I can attend at least half of the staff meetings.')),
                ('strikes_check', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have no strikes on my account currently')),
                ('role', models.TextField(help_text='What role are you applying for?', verbose_name='Roles')),
                ('why', models.TextField(help_text='Tell us why you want to be a MegaClan Staff Member. Be descriptive.', verbose_name='Why do you want to apply for staff?')),
                ('how_better', models.TextField(help_text='Tell us what you will do to make MC better as a staff member.', verbose_name='How do you think you can make MC better?')),
                ('read_requirements', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I confirm that I have read all the staff requirements and meet all of them.')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Staff Application',
                'verbose_name_plural': 'Staff Applications',
            },
        ),
        migrations.CreateModel(
            name='StaffApplyBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Staff Application Background Image',
                'verbose_name_plural': 'Staff Application Background Images',
            },
        ),
        migrations.CreateModel(
            name='StaffBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Staff Background Image',
                'verbose_name_plural': 'Staff Background Images',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here. If you wish to stay anonymous, put "Anonymous".', max_length=100)),
                ('position', models.CharField(help_text='Please let us know what staff position you serve currently.', max_length=200)),
                ('description', models.TextField(help_text='Write whatever you want on your profile here (within regulations).')),
                ('staff_feats', models.TextField(help_text='Let us know of your transcendental feats of making MegaClan a better place.', verbose_name='staff feats')),
                ('image', models.FileField(help_text='Please provide a cover image for your profile.', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Staff Ranks Background Image',
                'verbose_name_plural': 'Staff Ranks Background Images',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Website',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here. If you wish to stay anonymous, put "Anonymous".', max_length=100)),
                ('category', models.CharField(help_text='Please let us know what type of issue you are dealing with.', max_length=200)),
                ('issue', models.TextField(help_text='Describe your issue in detail. We will try to get back to you as soon as possible.')),
                ('Additional_comments', models.TextField(help_text='Put any additional comments you may have here.', verbose_name='additional comments')),
                ('image', models.ImageField(help_text='Please attach a screenshot of your issue.', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Customer Support',
                'verbose_name_plural': 'Customer Support',
            },
        ),
        migrations.CreateModel(
            name='SupportBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Support Background Image',
                'verbose_name_plural': 'Support Background Images',
            },
        ),
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SupportChatBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Support Chat Background Image',
                'verbose_name_plural': 'Support Chat Background Images',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=1000000)),
                ('room', models.CharField(max_length=1000000)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
        ),
        migrations.CreateModel(
            name='TagBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Tag Background Image',
                'verbose_name_plural': 'Tag Background Images',
            },
        ),
        migrations.CreateModel(
            name='TextBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('url', models.URLField(verbose_name='Page URL')),
                ('header_or_textfield', models.BooleanField(choices=[(1, 'Header'), (0, 'Body')], default=1, verbose_name='Header or Body Text')),
                ('section', models.IntegerField(help_text='Section Number of Text', verbose_name='Text Section')),
                ('exists', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, help_text='Is this section taken?', verbose_name='Section Taken')),
                ('hyperlink', models.TextField(blank=True, null=True, verbose_name='Hyperlink')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Text Base',
                'verbose_name_plural': 'Text Base',
            },
        ),
        migrations.CreateModel(
            name='TiersBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Tiers Background Image',
                'verbose_name_plural': 'Tiers Background Images',
            },
        ),
        migrations.CreateModel(
            name='Titled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtitle', models.TextField(verbose_name='Title')),
                ('page', models.TextField(blank=True, null=True, verbose_name='Page Name')),
                ('url', models.URLField(verbose_name='Page URL')),
                ('position', models.IntegerField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Page Title',
                'verbose_name_plural': 'Page Titles',
            },
        ),
        migrations.CreateModel(
            name='UpdateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name goes here.', max_length=100)),
                ('description', models.TextField(help_text='Your profile description goes here.')),
                ('image', models.ImageField(help_text='Attach an image for your profile (scales to your picture`s dimensions.)', upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'User Profile Post',
                'verbose_name_plural': 'User Profile Posts',
            },
        ),
        migrations.CreateModel(
            name='UserBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'User Background Image',
                'verbose_name_plural': 'Users Background Images',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name goes here.', max_length=100)),
                ('category', models.CharField(help_text='Type the category that you are voting on (server layout, event idea, administration position, etc).', max_length=100)),
                ('description', models.TextField(help_text='Please share any ideas you may have.')),
                ('image', models.ImageField(help_text='Attach an image for your profile (scales to your picture`s dimensions.)', upload_to='')),
                ('mfg_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='VoteBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Vote Background Image',
                'verbose_name_plural': 'Vote Background Images',
            },
        ),
        migrations.CreateModel(
            name='WebsiteBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Website Background Image',
                'verbose_name_plural': 'Website Background Images',
            },
        ),
        migrations.CreateModel(
            name='WhyBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Why Background Image',
                'verbose_name_plural': 'Why Background Images',
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('advertisementbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='showcase.advertisementbase')),
            ],
            bases=('showcase.advertisementbase',),
        ),
        migrations.CreateModel(
            name='UserProfile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edit Profile',
                'verbose_name_plural': 'Edit Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('one_click_purchasing', models.BooleanField(default=False)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Your username', max_length=200)),
                ('password', models.CharField(help_text='Your password', max_length=200)),
                ('coupons', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Send me coupons')),
                ('news', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Keep me in the loop')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active refund?')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='Profile picture')),
                ('alternate', models.TextField(verbose_name='Alternate text')),
                ('about_me', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Profile',
                'verbose_name_plural': 'Account Profiles',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to use corresponding product slug.', max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.item')),
                ('orderitem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.orderitem', verbose_name='Order item id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Item Fields',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='showcase.orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='showcase.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImageBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Advertisement title.', max_length=100, verbose_name='advertisement title')),
                ('image', models.ImageField(height_field='image_length', help_text='Image of the advertisement.', upload_to='images/', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(blank=True, default='100', help_text='Width of the image (in percent relative).', null=True, verbose_name='image width')),
                ('image_length', models.PositiveIntegerField(blank=True, default='100', help_text='Length of the image (in percent relative).', null=True, verbose_name='image length')),
                ('width_for_resize', models.PositiveIntegerField(default=600, verbose_name='Resize Width')),
                ('height_for_resize', models.PositiveIntegerField(default=40, verbose_name='Resize Height')),
                ('image_position', models.IntegerField(help_text='Positioning of the image.', verbose_name='Position')),
                ('alternate', models.TextField(verbose_name='Alternate Text')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('xposition', models.IntegerField(default='0', help_text='x-position.', verbose_name='x-position')),
                ('yposition', models.IntegerField(default='0', help_text='x-position.', verbose_name='y-position')),
                ('relevance', models.TextField(help_text='Relevance of advertisement')),
                ('type', models.CharField(help_text='Type of image.', max_length=200)),
                ('hyperlink', models.TextField(blank=True, null=True, verbose_name='Hyperlink')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('correlating_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.item')),
            ],
            options={
                'verbose_name': 'Image Base',
                'verbose_name_plural': 'Image Base',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperlink', models.CharField(blank=True, help_text='Leave field blank, hyperlink will automatically fill with the link to the associated product.', max_length=200, null=True)),
                ('comment', models.TextField()),
                ('feedbackpage', models.TextField(blank=True, null=True, verbose_name='Page Name')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to use corresponding product slug.', max_length=200, null=True)),
                ('star_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star Rating')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.orderitem')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='showcase.blog')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active address?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Checkout Addresses',
            },
        ),
        migrations.AddField(
            model_name='advertisementbase',
            name='correlating_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.item'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='1->Like, 2->Dislike')),
                ('date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='showcase.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Like',
                'verbose_name_plural': 'Blog Like',
                'unique_together': {('user', 'post', 'value')},
            },
        ),
    ]
