# Generated by Django 4.1.10 on 2024-12-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='participants',
        ),
    ]
