# Generated by Django 4.1.10 on 2024-07-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_hits_earnedachievements_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnedachievements',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.achievements'),
        ),
    ]
