# Generated by Django 4.1.10 on 2025-02-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_bet_winning_team_bet_winning_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='team_battle',
            field=models.BooleanField(default=False),
        ),
    ]
