# Generated by Django 4.2.20 on 2025-05-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_rubydrop_rubydropinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Season name goes here.', max_length=100)),
                ('season_length', models.IntegerField(help_text='In days')),
                ('description', models.TextField(help_text='Give a brief description of the event.')),
                ('date', models.DateField(help_text='Season date (day, date, and month)', null=True)),
                ('time', models.TimeField(help_text='Season time (hour/minute)', null=True)),
                ('date_and_time', models.DateTimeField(null=True, verbose_name='Time and date of Event Creation')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(help_text='Please provide a cover image for the event.', upload_to='images/')),
                ('image_length', models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length')),
                ('image_width', models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
        ),
    ]
