# Generated by Django 4.1.10 on 2024-06-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_inventoryobject_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='robots',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='inventoryobject',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='image',
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle',
            name='battle_name',
            field=models.CharField(default=1, help_text='Your name and tag go here.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_bot': True}, related_name='battles', to='showcase.battleparticipant'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='level',
            name='experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.experience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='alternate',
            field=models.TextField(default=1, verbose_name='Alternate text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='robot',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], max_length=1000),
        ),
    ]
