# Generated by Django 4.1.10 on 2024-03-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_tradeshippinglabel_responding_trade_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeshippinglabel',
            name='responding_trade_offer',
        ),
        migrations.AddField(
            model_name='respondingtradeoffer',
            name='trade_shipping_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.tradeshippinglabel'),
        ),
    ]
