# Generated by Django 4.1.10 on 2023-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_textbase_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbase',
            name='font_measurement',
            field=models.CharField(blank=True, choices=[('px', 'Pixels'), ('%', 'Percent'), ('vh', 'View Height'), ('em', 'em'), ('rem', 'Root em'), ('pt', 'Points'), ('pc', 'Picas')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='textbase',
            name='font_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Font Size'),
        ),
        migrations.AlterField(
            model_name='textbase',
            name='text_size',
            field=models.IntegerField(choices=[(6, 'H6'), (5, 'H5'), (4, 'H4'), (3, 'H3'), (2, 'H2'), (1, 'H1'), (0, 'p')], default=0, help_text='6->Body 3, 5->Body 2, 4->Body 1, 3-> Heading 3,2-> Heading 2, 1-> Heading 1,', verbose_name='Text Type'),
        ),
    ]
