# Generated by Django 4.1.10 on 2024-08-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_achievements_tradecontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='black_cards_hit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
