# Generated by Django 4.1.2 on 2023-06-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='E',
        ),
    ]
