# Generated by Django 4.1.10 on 2024-01-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_currency_shuffler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
