# Generated by Django 4.1.10 on 2024-12-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_remove_battle_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_bot': False}, related_name='battles', to='showcase.battleparticipant'),
        ),
    ]
