# Generated by Django 4.1.10 on 2024-08-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_profiledetails_black_cards_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawclass',
            options={'verbose_name': 'Withdrawal Class', 'verbose_name_plural': 'Withdrawal Classes'},
        ),
    ]
