# Generated by Django 4.1.10 on 2024-08-29 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerceexchange',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
        ),
    ]
