# Generated by Django 4.1.10 on 2024-03-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_remove_tradeshippinglabel_responding_trade_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='responding_trade_offers',
        ),
        migrations.AddField(
            model_name='respondingtradeoffer',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.trade'),
        ),
    ]
