# Generated by Django 4.1.10 on 2024-07-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_earnedachievements_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='earned',
            field=models.BooleanField(default=False),
        ),
    ]
