# Generated by Django 4.1.10 on 2025-02-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_battle_team_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.profiledetails'),
        ),
    ]
