# Generated by Django 4.1.2 on 2023-06-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_delete_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='image',
            field=models.URLField(help_text='Please attach a screenshot of your issue.'),
        ),
    ]
