# Generated by Django 4.1.10 on 2025-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_battleparticipant_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tophits',
            name='button_pressed',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
