# Generated by Django 5.1.6 on 2025-03-01 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_level_color_wheel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('level_icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Logo Item',
                'verbose_name_plural': 'Logo Items',
            },
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='level_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.levelicon'),
        ),
    ]
