# Generated by Django 4.2.20 on 2025-05-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='season',
            name='date',
            field=models.DateField(blank=True, help_text='Season date (day, date, and month)', null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='date_and_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date & time of event'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(help_text='Cover image', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image_length',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original length for ratio', null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original width for ratio', null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_length',
            field=models.PositiveIntegerField(help_text='In days'),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='time',
            field=models.TimeField(blank=True, help_text='Season time (hour/minute)', null=True),
        ),
    ]
