# Generated by Django 4.1.10 on 2024-08-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_commerceexchange_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': 'Invite Code', 'verbose_name_plural': 'Invite Codes'},
        ),
    ]
