# Generated by Django 4.1.2 on 2023-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_support_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='image',
            field=models.ImageField(help_text='Please attach a screenshot of your issue.', upload_to=''),
        ),
    ]
