# Generated by Django 4.1.10 on 2024-03-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_remove_trade_responding_trade_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondingtradeoffer',
            name='trade',
        ),
        migrations.AddField(
            model_name='trade',
            name='responding_trade_offer',
            field=models.ManyToManyField(to='showcase.respondingtradeoffer'),
        ),
    ]
