# Generated by Django 4.1.10 on 2024-12-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_remove_battle_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='robots',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_bot': True}, related_name='battles', to='showcase.robot'),
        ),
    ]
