# Generated by Django 4.1.10 on 2025-03-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_tophits_button_pressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryobject',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Sell-Locked'),
        ),
    ]
