# Generated by Django 5.1.6 on 2025-03-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_levelicon_profiledetails_level_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelicon',
            options={'verbose_name': 'Level Icon', 'verbose_name_plural': 'Level Icon'},
        ),
        migrations.AddField(
            model_name='levelicon',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
    ]
