# Generated by Django 4.2.20 on 2025-05-21 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_remove_season_is_active_alter_season_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
    ]
