# Generated by Django 4.1.10 on 2024-08-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_withdrawclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
