# Generated by Django 4.1.10 on 2024-06-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_battle_robots_inventoryobject_condition_robot_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='name',
        ),
        migrations.AddField(
            model_name='experience',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], default='N', max_length=1000),
        ),
        migrations.AlterField(
            model_name='inventoryobject',
            name='condition',
            field=models.CharField(blank=True, choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('D', 'Damaged')], default='M', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], default='N', max_length=1000),
        ),
        migrations.AlterField(
            model_name='level',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.experience'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='alternate',
            field=models.TextField(blank=True, null=True, verbose_name='Alternate text'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], default='N', max_length=1000),
        ),
    ]
