# Generated by Django 4.1.10 on 2024-03-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_alter_respondingtradeoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondingtradeoffer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
