# Generated by Django 5.1.6 on 2025-03-02 05:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_alter_levelicon_options_levelicon_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='color_wheel',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
