# Generated by Django 4.1.10 on 2024-03-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_remove_respondingtradeoffer_trade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='responding_trade_offer',
            new_name='responding_trade_offers',
        ),
    ]
