# Generated by Django 4.1.10 on 2025-02-26 04:44
from django.db import migrations, models
import django.db.models.deletion
import autoslug.fields
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_transaction_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Achievement Title')),
                ('slug', autoslug.fields.AutoSlugField(unique=True, editable=False)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_length', models.PositiveIntegerField(
                    blank=True,
                    null=True,
                    default=100,
                    help_text='Original length of the advertisement (use for original ratio).',
                    verbose_name='image length'
                )),
                ('image_width', models.PositiveIntegerField(
                    blank=True,
                    null=True,
                    default=100,
                    help_text='Original width of the advertisement (use for original ratio).',
                    verbose_name='image width'
                )),
                ('category', models.CharField(
                    blank=True,
                    null=True,
                    max_length=4,
                    choices=[('RS', 'Rubies Spent'), ('CRS', 'Rubies Collected'), ('TRS', 'Total Rubies Earned')]
                )),
                ('rubies_spent', models.IntegerField(blank=True, null=True)),
                ('rubies_collected', models.IntegerField(blank=True, null=True)),
                ('total_rubies_earned', models.IntegerField(blank=True, null=True)),
                ('earned', models.BooleanField(default=False)),
                ('green_counter', models.IntegerField(blank=True, null=True, default=0)),
                ('yellow_counter', models.IntegerField(blank=True, null=True, default=0)),
                ('orange_counter', models.IntegerField(blank=True, null=True, default=0)),
                ('red_counter', models.IntegerField(blank=True, null=True, default=0)),
                ('black_counter', models.IntegerField(blank=True, null=True, default=0)),
                ('gold_counter', models.IntegerField(blank=True, null=True, default=0)),
                ('redgold_counter', models.IntegerField(blank=True, null=True, default=0)),
                ('date_and_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date and time')),
                ('is_active', models.IntegerField(
                    blank=True,
                    null=True,
                    default=1,
                    choices=[(1, 'Active'), (0, 'Inactive')],
                    help_text='1->Active, 0->Inactive',
                    verbose_name='Set active?'
                )),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.achievements')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.gamehub')),
                ('user', models.ManyToManyField(related_name='earner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Earned Achievement',
                'verbose_name_plural': 'Earned Achievements',
            },
        ),
    ]
