# Generated by Django 5.1.6 on 2025-04-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_inventoryobject_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tophits',
            name='demonstration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='color',
            field=models.CharField(blank=True, choices=[('gray', 'Gray'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('black', 'Black'), ('gold', 'Gold')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='color',
            field=models.CharField(blank=True, choices=[('gray', 'Gray'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('black', 'Black'), ('gold', 'Gold')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='spinnerchoicerenders',
            name='color',
            field=models.CharField(blank=True, choices=[('gray', 'Gray'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('black', 'Black'), ('gold', 'Gold')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tophits',
            name='color',
            field=models.CharField(blank=True, choices=[('gray', 'Gray'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('black', 'Black'), ('gold', 'Gold')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='MyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spintype', models.CharField(choices=[('C', 'Classic'), ('S', 'Simultaneous'), ('I', 'Instant')], default='C', max_length=1)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Preference',
                'verbose_name_plural': 'My Preferences',
            },
        ),
    ]
