# Generated by Django 4.1.10 on 2024-06-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_remove_experience_name_experience_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryobject',
            name='condition',
            field=models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('D', 'Damaged')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='level',
            name='experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.experience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='alternate',
            field=models.TextField(default=1, verbose_name='Alternate text'),
            preserve_default=False,
        ),
    ]
