# Generated by Django 4.1.10 on 2024-08-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_withdraw_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is this withdraw active?'),
        ),
    ]
