# Generated by Django 4.1.10 on 2024-08-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_alter_invitecode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerceexchange',
            name='usercard',
            field=models.ManyToManyField(to='showcase.tradeitem'),
        ),
    ]
