# Generated by Django 4.2.20 on 2025-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_alter_season_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='prize',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
