# Generated by Django 4.1.10 on 2024-07-04 23:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0006_remove_experience_amount_remove_product_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='name',
        ),
        migrations.AddField(
            model_name='experience',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], default='N', max_length=1000),
        ),
        migrations.AlterField(
            model_name='battle',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='lower_nonce',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Lower bound nonce of Choice', max_digits=7, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='rarity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rarity of choice in percent (optional).', max_digits=9, null=True, verbose_name='Rarity (%)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='upper_nonce',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Upper bound nonce of Choice', max_digits=7, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.IntegerField(blank=True, help_text='Value of item in Rubicoins.', null=True, verbose_name='Value (Rubicoins)'),
        ),
        migrations.AlterField(
            model_name='inventoryobject',
            name='condition',
            field=models.CharField(blank=True, choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('D', 'Damaged')], default='M', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], default='N', max_length=1000),
        ),
        migrations.AlterField(
            model_name='level',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.experience'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='color',
            field=models.CharField(blank=True, choices=[('Gra', 'Gray'), ('Gre', 'Green'), ('Y', 'Yellow'), ('O', 'Orange'), ('R', 'Red'), ('B', 'Black'), ('G', 'Gold')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='alternate',
            field=models.TextField(blank=True, null=True, verbose_name='Alternate text'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
                ('inventory_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.inventoryobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
