# Generated by Django 4.1.10 on 2024-12-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_battle_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='slots',
            field=models.CharField(choices=[('2', '1v1'), ('3', '1v1v1'), ('4', '1v1v1v1'), ('5', '1ve5'), ('6', '1ve6'), ('7', '1ve7'), ('8', '1ve8'), ('9', '1ve9'), ('10', '1ve10'), ('2v2', '2v2'), ('2ve3', '2v2v2'), ('2ve4', '2v2v2v2'), ('2ve5', '2ve5'), ('3v3', '3v3'), ('3ve3', '3v3v3'), ('4v4', '4v4'), ('5v5', '5v5')], default='2', max_length=4),
        ),
    ]
