# Generated by Django 3.1.5 on 2021-11-11 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_auto_20211111_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default=django.utils.timezone.now, help_text='Link a URL for your profile (scales to your picture`s dimensions.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.URLField(default=django.utils.timezone.now, help_text='Link a URL for your profile (scales to your picture`s dimensions.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='image',
            field=models.URLField(help_text='Link a URL for your profile (scales to your picture`s dimensions.)'),
        ),
    ]
