# Generated by Django 4.1.10 on 2024-03-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_respondingtradeoffer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondingtradeoffer',
            options={'verbose_name': 'Trade Offer', 'verbose_name_plural': 'Trade Offers'},
        ),
    ]
