# Generated by Django 5.1.6 on 2025-03-02 22:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_level_color_wheel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='choices',
        ),
        migrations.AlterField(
            model_name='level',
            name='color_wheel',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
