# Generated by Django 4.2.20 on 2025-05-27 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_lottery_prize_season_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(blank=True, choices=[('F', 'Free'), ('G', 'Gambler'), ('D', 'Degen'), ('W', 'Whale'), ('HR', 'High Roller'), ('M', 'Monstrosity')], max_length=2, null=True)),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Sprite')),
                ('description', models.TextField(blank=True, null=True)),
                ('image_length', models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length')),
                ('image_width', models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width')),
                ('lower_bound', models.FloatField(default=0)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('timeframe', models.DurationField(default=datetime.timedelta(days=30), help_text='How far back to include (defaults to 30 days)')),
                ('mfg_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Tier',
                'verbose_name_plural': 'Tiers',
            },
        ),
    ]
