# Generated by Django 4.1.10 on 2024-08-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_withdraw_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='image',
        ),
    ]
