# Generated by Django 4.1.10 on 2025-02-26 04:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_delete_earnedachievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnedachievements',
            name='category',
            field=models.CharField(blank=True, choices=[('RS', 'Rubies Spent'), ('TRE', 'Total Rubies Earned '), ('RC', 'Rubies Collected'), ('WS', 'Wheels Spun'), ('GCH', 'Green Cards Hit'), ('YCH', 'Yellow Cards Hit'), ('OCH', 'Orange Cards Hit'), ('RCH', 'Red Cards Hit'), ('BCH', 'Black Cards Hit'), ('GOCH', 'Gold Cards Hit'), ('RGCH', 'Red Gold Cards Hit'), ('BW', 'Battles Won'), ('BL', 'Battles Lost'), ('BD', 'Battles Drawn'), ('FA', 'Friends Added'), ('TCS', 'Total Community Size'), ('O', 'Other')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='earnedachievements',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='earnedachievements',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
    ]
