# Generated by Django 4.1.2 on 2023-06-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_support_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(help_text='Please provide a cover image for your profile.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='image',
            field=models.ImageField(help_text='Please provide a cover image for the news.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='image',
            field=models.ImageField(help_text='Please put a screenshot of the issue.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(help_text='Please provide a cover image for your profile.', upload_to=''),
        ),
    ]
