# Generated by Django 4.1.10 on 2024-07-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_achievements_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
            preserve_default=False,
        ),
    ]
