# Generated by Django 4.1.10 on 2024-08-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_commerceexchange_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprize',
            name='condition',
            field=models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('D', 'Damaged')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='exchangeprize',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
        ),
        migrations.AddField(
            model_name='exchangeprize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exchangeprize',
            name='image_length',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length'),
        ),
        migrations.AddField(
            model_name='exchangeprize',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width'),
        ),
        migrations.AddField(
            model_name='exchangeprize',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.choice'),
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
