# Generated by Django 4.1.10 on 2024-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_remove_withdraw_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={},
        ),
        migrations.AddField(
            model_name='withdraw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='withdraw_images/'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this withdraw active?'),
        ),
    ]
