# Generated by Django 4.1.10 on 2024-01-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_shuffletype_shuffler_demonstration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='number',
            field=models.IntegerField(default=1, help_text='Position in rarity (ordered by value)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerversusplayer',
            name='privacy',
            field=models.CharField(default=1, max_length=3, verbose_name=(('PUB', 'Public'), ('PRI', 'Private'))),
            preserve_default=False,
        ),
    ]
