# Generated by Django 5.1.6 on 2025-03-03 00:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_remove_game_choices_alter_level_color_wheel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='color_wheel',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
