# Generated by Django 4.1.10 on 2024-08-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_exchangeprize_condition_exchangeprize_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerceexchange',
            old_name='value',
            new_name='total_prize_value',
        ),
        migrations.AddField(
            model_name='commerceexchange',
            name='total_usercard_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commerceexchange',
            name='value_descrepancy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
