# Generated by Django 4.1.2 on 2023-06-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_alter_event_image_alter_newsfeed_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(help_text='Please provide a cover image for your profile.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='image',
            field=models.FileField(help_text='Please provide a cover image for the news.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='image',
            field=models.FileField(help_text='Please put a screenshot of the issue.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=models.FileField(help_text='Please provide a cover image for your profile.', upload_to=''),
        ),
    ]
