# Generated by Django 4.1.10 on 2024-03-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_alter_respondingtradeoffer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondingtradeoffer',
            options={'verbose_name': 'Trade Offer Response', 'verbose_name_plural': 'Trade Offer Responses'},
        ),
    ]
