# Generated by Django 4.1.10 on 2024-08-02 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0007_achievements_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField(default=10)),
                ('trading_contract', models.TextField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Trade Contract',
                'verbose_name_plural': 'Trade Contracts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tradeshippinglabel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.itemfilter'),
        ),
        migrations.CreateModel(
            name='TradeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_confirmation', models.BooleanField(default=False, verbose_name='I confirm that I agree to these terms & conditions for the trade.')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeconfirm', to='showcase.trade')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traderconfirm', to=settings.AUTH_USER_MODEL)),
                ('trading_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='showcase.trade')),
            ],
            options={
                'verbose_name': 'Trade Confirmation',
                'verbose_name_plural': 'Trade Confirmations',
            },
        ),
    ]
