# Generated by Django 4.2.20 on 2025-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='lower_bound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('F', 'Free'), ('G', 'Gambler'), ('D', 'Degen'), ('W', 'Whale'), ('HR', 'High Roller'), ('G', 'GOAT'), ('M', 'Monstrosity')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='upper_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
