# Generated by Django 5.1.6 on 2025-04-09 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_giftcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='currency_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('S', 'Sale'), ('B', 'Bonus')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
