# Generated by Django 4.1.10 on 2024-12-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_alter_battle_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='bets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('F', 'Free For All'), ('UD', 'Upside-Down'), ('T', 'Teams'), ('DW', 'Dual Win'), ('TF', 'Team Fight'), ('DL', 'Do Not Lose'), ('S', 'Share')], default='F', max_length=2),
        ),
    ]
