# Generated by Django 5.1.6 on 2025-03-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_alter_level_color_wheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_state',
            field=models.CharField(choices=[('I', 'Incomplete'), ('C', 'Complete')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.99, max_digits=10, null=True),
        ),
    ]
