# Generated by Django 3.1.5 on 2021-11-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
