# Generated by Django 4.1.10 on 2024-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_choice_number_playerversusplayer_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='rarity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rarity of choice in percent (optional).', max_digits=7, null=True, verbose_name='Rarity (%)'),
        ),
    ]
