# Generated by Django 4.1.10 on 2024-03-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_alter_respondingtradeoffer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile2',
            options={'verbose_name': 'Shipping Profile', 'verbose_name_plural': 'Shipping Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile2',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
