# Generated by Django 4.1.10 on 2024-12-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_battle_bets_allowed_battle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('Free For All', 'Free For All'), ('Upside-Down', 'Upside-Down'), ('Teams', 'Teams'), ('Dual Win', 'Dual Win'), ('Team Fight', 'Team Fight'), ('Do Not Lose', 'Do Not Lose'), ('Share', 'Share')], default='Free For All', max_length=20),
        ),
    ]
