# Generated by Django 4.1.2 on 2023-06-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_alter_event_image_alter_newsfeed_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='link_to_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.profiledetails', verbose_name='Link to profile'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
