# Generated by Django 4.1.10 on 2024-08-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_alter_withdraw_options_remove_withdraw_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawclass',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
            preserve_default=False,
        ),
    ]
