# Generated by Django 4.1.10 on 2024-03-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_alter_userprofile2_options_userprofile2_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile2',
            name='phone',
            field=models.IntegerField(default='000-000-0000'),
        ),
    ]
