# Generated by Django 4.1.2 on 2023-06-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_profiledetails_link_to_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='link_to_profile',
        ),
    ]
