# Generated by Django 4.2.20 on 2025-05-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_benefits_alter_tier_image_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='benefits',
        ),
        migrations.DeleteModel(
            name='Benefits',
        ),
    ]
