# Generated by Django 3.1.5 on 2021-11-29 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_auto_20211129_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Post your profile here.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Your name goes here.', max_length=100),
            preserve_default=False,
        ),
    ]
