# Generated by Django 5.1.6 on 2025-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_withdraw_withdraw_state_alter_withdraw_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='fees',
            field=models.IntegerField(blank=True, default=599, null=True),
        ),
    ]
