# Generated by Django 4.1.10 on 2024-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_alter_battle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
