# Generated by Django 5.1.6 on 2025-04-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_coupon_user_coupon_uses_giftcode_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='uses',
            field=models.IntegerField(default=1),
        ),
    ]
