# Generated by Django 4.1.10 on 2024-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_order_currencyorderprice_order_orderprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currencyorderprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
