# Generated by Django 4.1.10 on 2024-08-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_remove_tradeitem_choice_tradeitem_inventoryobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryobject',
            name='length_for_resize',
            field=models.PositiveIntegerField(default=100, verbose_name='Resized Length'),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='width_for_resize',
            field=models.PositiveIntegerField(default=100, verbose_name='Resized Width'),
        ),
    ]
