# Generated by Django 4.2.20 on 2025-05-28 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_remove_tier_benefits_delete_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='timeframe',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=30), help_text='How far back to include (defaults to 30 days)', null=True),
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(choices=[('RD', 'Ruby Drop'), ('DC', 'Daily Chests'), ('RR', 'Referal Rubies')], max_length=2)),
                ('multiplier', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.tier')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
        ),
    ]
