# Generated by Django 4.1.10 on 2024-03-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_alter_userprofile2_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile2',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
