# Generated by Django 4.1.10 on 2024-08-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_withdrawclass_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='condition',
            field=models.CharField(blank=True, choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('D', 'Damaged')], default='M', max_length=2, null=True),
        ),
    ]
