# Generated by Django 5.1.6 on 2025-04-09 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_giftcode_uses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcode',
            options={'verbose_name': 'Gift Code', 'verbose_name_plural': 'Gift Codes'},
        ),
        migrations.AlterModelOptions(
            name='levelicon',
            options={'verbose_name': 'Level Icon', 'verbose_name_plural': 'Level Icons'},
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='code',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='serial',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GiftCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('gift_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.giftcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gift_code')},
            },
        ),
    ]
