# Generated by Django 4.1.10 on 2024-08-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_orderitem_currencyorderprice_orderitem_orderprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currencyorderprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Currency order price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderprice',
            field=models.FloatField(blank=True, null=True, verbose_name='Order price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currencyorderprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Curency order price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderprice',
            field=models.FloatField(blank=True, null=True, verbose_name='Order price'),
        ),
    ]
