# Generated by Django 5.1.6 on 2025-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_alter_withdraw_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='capacity_state',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
