# Generated by Django 4.2.20 on 2025-05-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_alter_tier_timeframe_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.tier'),
        ),
    ]
