# Generated by Django 4.1.10 on 2024-07-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_item_multi_listing_quickitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_length2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_length3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_length4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_length5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_width2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_width3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_width4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_width5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length_for_resize',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length_for_resize2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length_for_resize3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length_for_resize4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length_for_resize5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_for_resize',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_for_resize2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_for_resize3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_for_resize4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_for_resize5',
        ),
    ]
