# Generated by Django 5.1.6 on 2025-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_alter_giftcode_options_alter_levelicon_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
