# Generated by Django 4.1.10 on 2024-08-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_alter_order_currencyorderprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='billing_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
