# Generated by Django 5.1.6 on 2025-03-05 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_withdraw_capacity_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyorder',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.currencymarket'),
        ),
    ]
