# Generated by Django 4.1.2 on 2023-07-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_alter_settingsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Attach an image for your profile (scales to your picture`s dimensions.)', null=True, upload_to=''),
        ),
    ]
