# Generated by Django 4.1.10 on 2024-08-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_withdraw_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryobject',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of items available.'),
        ),
    ]
