# Generated by Django 4.1.10 on 2024-01-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_alter_shuffler_shuffletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffler',
            name='shuffletype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.shuffletype', verbose_name='Shuffle Type'),
        ),
    ]
