# Generated by Django 5.1.6 on 2025-04-09 07:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import showcase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_alter_giftcode_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='total_uses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='tracking_total_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='value',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='giftcoderedemption',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='expiration_date',
            field=models.DateTimeField(default=showcase.models.default_expiration),
        ),
    ]
