# Generated by Django 4.1.10 on 2024-03-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_alter_userprofile2_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile2',
            old_name='country',
            new_name='state',
        ),
    ]
