# Generated by Django 4.1.10 on 2024-07-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_remove_item_image2_remove_item_image3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickitem',
            options={'verbose_name': 'Quick Item', 'verbose_name_plural': 'Quick Items'},
        ),
        migrations.AddField(
            model_name='item',
            name='image_length',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width'),
        ),
        migrations.AddField(
            model_name='item',
            name='length_for_resize',
            field=models.PositiveIntegerField(default=100, verbose_name='Resized Length'),
        ),
        migrations.AddField(
            model_name='item',
            name='width_for_resize',
            field=models.PositiveIntegerField(default=100, verbose_name='Resized Width'),
        ),
    ]
