# Generated by Django 5.1.6 on 2025-03-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_alter_currencyorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymarket',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
