# Generated by Django 4.2.20 on 2025-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_profiledetails_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='total_card_money_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Money Spent On Cards (USD)'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='total_currency_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Money Spent On Rubies (USD)'),
        ),
    ]
