# Generated by Django 4.1.10 on 2024-08-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_inventoryobject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='certified',
            field=models.BooleanField(default=False, help_text='If you are applying to become a partner in more than 1 category, talk to Trove.'),
        ),
    ]
