# Generated by Django 4.1.10 on 2024-08-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_inventoryobject_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='subcategory',
            field=models.CharField(default=1, help_text='Subcategory of choice (Pokemon, trainers, etc.).', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='category',
            field=models.CharField(help_text='Category of choice (Pokemon, Yu-Gi-Oh, Bakugo, Magic The Gathering, etc.).', max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='number_of_choice',
            field=models.IntegerField(default=1),
        ),
    ]
