# Generated by Django 4.2.20 on 2025-05-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_profiledetails_total_card_money_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='total_currency_spent_30',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='30-Day Money Spent On Rubies (USD)'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='total_currency_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Money Spent On Rubies (USD)'),
        ),
    ]
