# Generated by Django 5.1.6 on 2025-03-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_alter_currencymarket_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clickable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Clickable Image')),
                ('value', models.IntegerField(default=0)),
                ('rarity', models.IntegerField(default=0)),
                ('chance_per_thousand', models.IntegerField(default=1000)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
            ],
        ),
    ]
