# Generated by Django 4.1.10 on 2024-12-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_profiledetails_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='second_discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='second_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
