# Generated by Django 4.1.10 on 2024-03-07 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0013_rename_country_userprofile2_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile2',
            name='zip_code',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile2',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ship_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile2',
            unique_together={('user', 'id')},
        ),
    ]
