# Generated by Django 5.1.6 on 2025-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_giftcode_currency_giftcode_total_uses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcoderedemption',
            options={'verbose_name': 'Gift Code Redemption', 'verbose_name_plural': 'Gift Codes Redemptions'},
        ),
        migrations.AddField(
            model_name='currencyfullorder',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, help_text='Stripe charge ID', max_length=255, null=True),
        ),
    ]
