# Generated by Django 4.1.2 on 2023-07-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_alter_updateprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofile',
            name='category',
            field=models.CharField(default=1, help_text='Please let us know what type of issue you are dealing with.', max_length=200),
            preserve_default=False,
        ),
    ]
