# Generated by Django 4.1.10 on 2024-01-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_alter_shuffler_shuffletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerversusplayer',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
        migrations.AddField(
            model_name='playerversusplayer',
            name='locked_in',
            field=models.BooleanField(default=0, help_text='0->Open, 1->Locked In', verbose_name='Open or Locked In?'),
        ),
        migrations.AddField(
            model_name='shuffletype',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
    ]
