# Generated by Django 4.1.10 on 2024-08-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_choice_subcategory_alter_choice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Subcategory of choice (Pokemon, trainers, etc.).', max_length=200, null=True),
        ),
    ]
