# Generated by Django 3.1.5 on 2021-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your discord name & tag.', max_length=100)),
                ('I_have_been_in_MC_for_at_least_2_months', models.BooleanField()),
                ('I_have_been_in_a_previous_role_for_at_least_1_month', models.BooleanField()),
                ('I_can_attend_at_least_half_of_the_staff_meetings', models.BooleanField()),
                ('I_have_no_strikes_on_my_account_currently', models.BooleanField()),
                ('role', models.TextField(help_text='What role are you applying for?')),
                ('Why_do_you_want_to_apply_for_staff', models.TextField(help_text='Tell us why you want to be a MegaClan Staff Member. Be descriptive.')),
                ('How_do_you_think_you_can_make_MC_better', models.TextField(help_text='Tell us what you will do to make MC better as a staff member.')),
                ('I_confirm_that_I_have_read_all_the_staff_requiernments_and_meet_all_of_them', models.BooleanField()),
            ],
        ),
    ]
