# Generated by Django 4.1.10 on 2024-12-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_membership_second_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='Rubies', max_length=200),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(default='Rubies', max_length=200),
        ),
    ]
