# Generated by Django 4.1.10 on 2024-08-28 23:40

from django.db import migrations, models

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_alter_choice_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='number',
            field=models.IntegerField(blank=True, default=1, help_text='Position ordered by value (from highest to lowest)', null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('inventory_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.inventoryobject')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('date_and_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time and date')),
            ],
        ),
    ]
