# Generated by Django 4.1.10 on 2024-07-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='currency_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
