# Generated by Django 4.1.10 on 2024-08-06 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_administrationchangelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrationchangelog',
            old_name='model_name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='administrationchangelog',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='administrationchangelog',
            name='changed_data',
        ),
        migrations.AddField(
            model_name='administrationchangelog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationchangelog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrationchangelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
