# Generated by Django 4.1.2 on 2023-07-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_updateprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofile',
            name='category',
        ),
    ]
