# Generated by Django 4.1.10 on 2024-01-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_playerversusplayer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuffler',
            name='name',
        ),
        migrations.AddField(
            model_name='shuffler',
            name='choices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shuffler',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.pollquestion'),
        ),
    ]
