# Generated by Django 5.1.6 on 2025-04-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_alter_giftcoderedemption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currencyorderprice',
            field=models.IntegerField(default=0, verbose_name='Currency order price'),
        ),
    ]
