# Generated by Django 4.2.20 on 2025-05-28 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_profiledetails_total_currency_spent_30_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
