# Generated by Django 4.1.10 on 2024-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_remove_shuffler_name_shuffler_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuffletype',
            name='game_mode',
            field=models.CharField(default='STP', max_length=3, verbose_name=(('STW', 'Spin The Wheel'), ('OB', 'Open Box'), ('OP', 'Open Pack'), ('SR', 'Spin Roulette'))),
        ),
    ]
