# Generated by Django 4.1.10 on 2024-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_rename_model_name_administrationchangelog_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrationchangelog',
            options={'verbose_name': 'Administration Changelog', 'verbose_name_plural': 'Administration Changelogs'},
        ),
        migrations.AlterField(
            model_name='tradecontract',
            name='commission',
            field=models.FloatField(default=10, help_text='(%)'),
        ),
    ]
