# Generated by Django 4.1.10 on 2024-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_alter_profiledetails_currency_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
