# Generated by Django 4.1.10 on 2024-03-08 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0015_rename_phone_userprofile2_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default=0, max_length=5)),
                ('phone_number', models.CharField(default='000-000-0000', max_length=12)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade Shipping Profile',
                'verbose_name_plural': 'Trade Shipping Profiles',
                'unique_together': {('user', 'id')},
            },
        ),
    ]
