# Generated by Django 4.2.20 on 2025-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_profiledetails_created_at_profiledetails_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('F', 'Free'), ('G', 'Gambler'), ('D', 'Degen'), ('W', 'Whale'), ('HR', 'High Roller'), ('G', 'GOAT'), ('M', 'Monstrosity')], default='B', max_length=2, null=True),
        ),
    ]
