# Generated by Django 4.1.2 on 2023-07-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_remove_updateprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='link_to_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.profiledetails', verbose_name='Link to profile'),
        ),
    ]
