# Generated by Django 5.1.6 on 2025-04-10 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_alter_order_currencyorderprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderprice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Order price'),
        ),
    ]
