# Generated by Django 4.1.10 on 2024-11-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_choice_currency_alter_outcome_nonce_gamehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='position',
        ),
        migrations.RemoveField(
            model_name='currencyorder',
            name='profile',
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='Rubiaces', max_length=200),
        ),
        migrations.AlterField(
            model_name='currencyorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_billing_address', to='showcase.address'),
        ),
        migrations.AlterField(
            model_name='currencyorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_shipping_address', to='showcase.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='showcase.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='showcase.address'),
        ),
    ]
