# Generated by Django 4.1.10 on 2024-12-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_alter_currency_name_alter_membership_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monstrosity',
            options={'verbose_name': 'Monstrosity', 'verbose_name_plural': 'Monstrosities'},
        ),
        migrations.AlterField(
            model_name='monstrosity',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monstrosity',
            name='monstrositys_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
