# Generated by Django 4.2.20 on 2025-05-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_alter_tier_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('F', 'Free'), ('G', 'Gambler'), ('P', 'Plunger'), ('D', 'Degen'), ('W', 'Whale'), ('BA', 'Baller'), ('GT', 'GOAT'), ('M', 'Monstrosity')], default='B', max_length=2, null=True),
        ),
    ]
