# Generated by Django 5.1.6 on 2025-03-15 08:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_alter_game_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickable',
            old_name='value',
            new_name='base_value',
        ),
        migrations.RenameField(
            model_name='clickable',
            old_name='chance_per_thousand',
            new_name='chance_per_second',
        ),
        migrations.RemoveField(
            model_name='clickable',
            name='currency',
        ),
        migrations.AddField(
            model_name='choice',
            name='attacks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='evolves_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='hp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='image_large',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='midcategory',
            field=models.CharField(blank=True, help_text='Middle category of choice.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='retreat_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='set_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='set_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='set_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='subtypes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='supertype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.IntegerField(blank=True, help_text='Value of item in Rubies.', null=True, verbose_name='Value (Rubies)'),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='value',
            field=models.IntegerField(blank=True, help_text='Value of item in Rubies.', null=True, verbose_name='Value (Rubies)'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_state',
            field=models.CharField(choices=[('I', 'Incomplete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='I', max_length=2),
        ),
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('rarity', models.DecimalField(blank=True, decimal_places=6, help_text='Rarity of choice in percent (optional).', max_digits=9, null=True, verbose_name='Rarity (%)')),
                ('lower_nonce', models.IntegerField(help_text='Lower bound nonce of Choice', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('upper_nonce', models.IntegerField(help_text='Upper bound nonce of Choice', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.choice')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.game')),
            ],
            options={
                'unique_together': {('game', 'choice')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='api_set_cards', through='showcase.GameChoice', to='showcase.choice'),
        ),
        migrations.CreateModel(
            name='UserClickable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exponential_level_multiplier', models.FloatField(default=1.0)),
                ('actual_value', models.FloatField(default=0)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('clickable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.clickable')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Clickable',
                'verbose_name_plural': 'User Clickables',
            },
        ),
    ]
