# Generated by Django 4.1.10 on 2024-08-08 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0016_alter_administrationchangelog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradeshippinglabel',
            options={'verbose_name': 'Trade Shipping Label', 'verbose_name_plural': 'Trade Shipping Labels'},
        ),
        migrations.AddField(
            model_name='tradeshippinglabel',
            name='shipping_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.userprofile2'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlogTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField(unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on: ')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Tip',
                'verbose_name_plural': 'Blog Tips',
            },
        ),
    ]
