# Generated by Django 4.1.10 on 2024-03-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_tradeshippinglabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='responding_trade_offers',
            field=models.ManyToManyField(to='showcase.respondingtradeoffer'),
        ),
    ]
