# Generated by Django 5.1.6 on 2025-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_alter_order_orderprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='heat',
            field=models.CharField(blank=True, choices=[('M', 'Mild'), ('S', 'Spicy'), ('F', 'Fiery'), ('W', 'Wild'), ('E', 'Explosive')], max_length=2, null=True),
        ),
    ]
