# Generated by Django 4.1.10 on 2024-12-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_alter_battleparticipant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='items',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_inventory',
        ),
    ]
