# Generated by Django 4.1.10 on 2024-01-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_shuffletype_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffletype',
            name='circumstance',
            field=models.CharField(choices=[('OP', 'One Player'), ('PVP', 'Player Versus Player'), ('MP', 'Multiple Players'), ('T', 'Tournament'), ('OE', 'Other Event'), ('L', 'Limited'), ('D', 'Drop')], default='OP', max_length=3),
        ),
        migrations.AlterField(
            model_name='shuffletype',
            name='game_mode',
            field=models.CharField(choices=[('STW', 'Spin The Wheel'), ('OB', 'Open Box'), ('OP', 'Open Pack'), ('SR', 'Spin Roulette')], default='STP', max_length=3),
        ),
        migrations.AlterField(
            model_name='shuffletype',
            name='type',
            field=models.CharField(choices=[('L', 'Luck'), ('S', 'Skill'), ('G', 'Grade')], default='L', max_length=1),
        ),
    ]
