# Generated by Django 4.1.10 on 2024-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_remove_currency_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationchangelog',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
