# Generated by Django 5.1.6 on 2025-03-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_alter_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='attacks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='card_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='evolves_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='hp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='image_large',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='retreat_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='set_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='set_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='set_series',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='subtypes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='supertype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
