# Generated by Django 4.1.2 on 2023-07-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_profiledetails_link_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='link_to_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
