# Generated by Django 5.1.6 on 2025-03-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_choice_attacks_choice_card_id_choice_evolves_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='set_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='set_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
