# Generated by Django 4.1.2 on 2023-07-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_alter_profiledetails_link_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='link_to_profile',
        ),
    ]
