# Generated by Django 4.1.10 on 2024-03-09 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_trade_responding_trade_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeshippinglabel',
            name='responding_trade_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.respondingtradeoffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeshippinglabel',
            name='trade_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.tradeoffer'),
            preserve_default=False,
        ),
    ]
