# Generated by Django 5.1.6 on 2025-03-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_rename_value_clickable_base_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
