# Generated by Django 4.1.10 on 2024-08-08 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0017_alter_tradeshippinglabel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='quick_spin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpinPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_spin', models.BooleanField(default=False)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spinpreferer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spin Preference',
                'verbose_name_plural': 'Spin Preferences',
            },
        ),
    ]
