# Generated by Django 4.1.10 on 2024-12-12 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_profiledetails_monstrosity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='monstrosity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster', to='showcase.monstrosity'),
        ),
    ]
