# Generated by Django 5.1.6 on 2025-04-11 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_game_heat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypreferences',
            options={'verbose_name': 'My Preferences'},
        ),
        migrations.AlterUniqueTogether(
            name='mypreferences',
            unique_together={('user',)},
        ),
    ]
