# Generated by Django 4.1.10 on 2024-11-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_alter_administrationchangelog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationchangelog',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
