# Generated by Django 4.1.10 on 2024-07-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_generalmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalmessage',
            options={'verbose_name': 'General Message', 'verbose_name_plural': 'General Messages'},
        ),
    ]
