# Generated by Django 4.2.20 on 2025-05-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_alter_tier_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='showcase.tier'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('F', 'Free'), ('G', 'Gambler'), ('S', 'Shark'), ('D', 'Degen'), ('W', 'Whale'), ('BA', 'Baller'), ('GT', 'GOAT'), ('M', 'Monstrosity')], default='B', max_length=2, null=True),
        ),
    ]
