# Generated by Django 4.1.10 on 2024-12-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_remove_game_category_remove_game_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(default=1, help_text='Category of choice (Pokemon, Yu-Gi-Oh, Bakugo, Magic The Gathering, etc.).', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='items',
            field=models.ManyToManyField(related_name='official_items', to='showcase.prizepool'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
