# Generated by Django 5.1.6 on 2025-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_alter_choice_set_name_alter_choice_set_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='api_set_cards', to='showcase.choice'),
        ),
    ]
