# Generated by Django 4.1.10 on 2024-08-14 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0018_outcome_quick_spin_spinpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='user',
        ),
        migrations.AddField(
            model_name='achievements',
            name='user',
            field=models.ManyToManyField(related_name='achiever', to=settings.AUTH_USER_MODEL),
        ),
    ]
