# Generated by Django 4.1.10 on 2024-12-12 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_alter_profiledetails_monstrosity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonstrositySprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Monstrosity Sprite',
                'verbose_name_plural': 'Monstrosity Sprites',
            },
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
        ),
    ]
