# Generated by Django 4.1.10 on 2025-03-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_choice_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='total_number',
            field=models.IntegerField(blank=True, default=1, help_text='Position ordered by value (from highest to lowest)', null=True),
        ),
    ]
