# Generated by Django 3.1.5 on 2021-12-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_auto_20211230_0620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Idea',
        ),
        migrations.RenameModel(
            old_name='ShowcasePost',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='Poste',
            new_name='Vote',
        ),
    ]
