# Generated by Django 4.2.20 on 2025-05-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_alter_benefits_tier_alter_tier_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickable',
            name='lore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
