# Generated by Django 4.1.10 on 2024-01-15 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_choice_nodes_choice_nonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='nonce',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Nonce of choice', max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
