# Generated by Django 4.1.10 on 2024-07-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_alter_generalmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmessage',
            name='cutoff',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalmessage',
            name='message_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
