# Generated by Django 4.1.10 on 2024-08-15 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0019_remove_achievements_user_achievements_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='achiever', to=settings.AUTH_USER_MODEL),
        ),
    ]
