# Generated by Django 4.1.10 on 2024-07-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_generalmessage_cutoff_generalmessage_message_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmessage',
            name='cutoff',
            field=models.IntegerField(default=0),
        ),
    ]
