# Generated by Django 5.1.6 on 2025-04-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_favoritechests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='favorite_chests',
            field=models.ManyToManyField(blank=True, to='showcase.favoritechests'),
        ),
    ]
