# Generated by Django 5.1.6 on 2025-03-08 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_game_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cards',
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.IntegerField(blank=True, help_text='Value of item in Rubies.', null=True, verbose_name='Value (Rubies)'),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='value',
            field=models.IntegerField(blank=True, help_text='Value of item in Rubies.', null=True, verbose_name='Value (Rubies)'),
        ),
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_nonce', models.IntegerField(help_text='Lower bound nonce of Choice', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('upper_nonce', models.IntegerField(help_text='Upper bound nonce of Choice', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.choice')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.game')),
            ],
            options={
                'unique_together': {('game', 'choice')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='api_set_cards', through='showcase.GameChoice', to='showcase.choice'),
        ),
    ]
