# Generated by Django 4.1.10 on 2024-01-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_alter_choice_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=500, verbose_name='Question')),
                ('mfg_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Prize Pool',
                'verbose_name_plural': 'Prize Pools',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.prizepool'),
        ),
    ]
