# Generated by Django 4.1.10 on 2024-12-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_monstrositysprite_alter_profiledetails_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstrosity',
            name='monstrositysprite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.monstrositysprite'),
            preserve_default=False,
        ),
    ]
