# Generated by Django 4.2.20 on 2025-06-01 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0020_changelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='model',
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('update', 'Update'), ('maintenance', 'Maintenance'), ('bugfix', 'Bugfix'), ('urgent', 'Urgent')], max_length=11),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
