# Generated by Django 4.1.10 on 2025-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_alter_orderitem_currencyorderprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currencyorderprice',
            field=models.IntegerField(default=0, verbose_name='Curency order price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderprice',
            field=models.FloatField(default=0, verbose_name='Order price'),
        ),
    ]
