# Generated by Django 5.1.6 on 2025-04-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_profiledetails_favorite_chests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='cards_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='black_cards_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='gold_cards_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='green_cards_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='orange_cards_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='red_cards_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='red_gold_cards_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='yellow_cards_hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
