# Generated by Django 3.1.5 on 2021-12-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_news_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.URLField(help_text='Link a URL for your idea (scales to your picture`s dimensions.)'),
        ),
    ]
