# Generated by Django 4.1.10 on 2024-12-12 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_monstrosity_monstrositysprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstrosity',
            name='monstrositys_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Monstrosity Name'),
        ),
        migrations.AlterField(
            model_name='monstrosity',
            name='monstrositysprite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.monstrositysprite', verbose_name='Monstrosity Sprite'),
        ),
    ]
