# Generated by Django 5.1.6 on 2025-03-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_remove_game_cards_alter_choice_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='midcategory',
            field=models.CharField(blank=True, help_text='Middle category of choice.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamechoice',
            name='rarity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rarity of choice in percent (optional).', max_digits=9, null=True, verbose_name='Rarity (%)'),
        ),
        migrations.AddField(
            model_name='gamechoice',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
