# Generated by Django 5.1.6 on 2025-03-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_choice_midcategory_gamechoice_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='card_id',
            field=models.CharField(max_length=100),
        ),
    ]
