# Generated by Django 4.1.10 on 2024-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_alter_choice_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='nodes',
            field=models.IntegerField(blank=True, help_text='Number of the choice included', null=True, verbose_name='Quantity Displayed'),
        ),
    ]
