# Generated by Django 5.1.6 on 2025-04-12 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_profiledetails_cards_counter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualChestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('plays', models.IntegerField(default=0)),
                ('chests', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalChestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('plays', models.IntegerField(default=0)),
                ('chests', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.game')),
            ],
        ),
    ]
