# Generated by Django 4.1.10 on 2024-01-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_pollquestion_is_active_prizepool_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='prize',
        ),
        migrations.AlterField(
            model_name='prizepool',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.choice'),
        ),
    ]
