# Generated by Django 4.1.10 on 2024-12-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_alter_monstrosity_monstrositys_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstrosity',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
