# Generated by Django 4.1.10 on 2025-03-19 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_alter_order_currencyorderprice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultavatar',
            options={'verbose_name': 'Default Avatar', 'verbose_name_plural': 'Default Avatar'},
        ),
        migrations.AlterField(
            model_name='gamechoice',
            name='lower_nonce',
            field=models.IntegerField(blank=True, help_text='Lower bound nonce of Choice', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
