# Generated by Django 3.1.5 on 2021-12-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_auto_20211230_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_Feed',
            new_name='NewsFeed',
        ),
    ]
