# Generated by Django 4.1.10 on 2024-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_achievements_tier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='tier',
            new_name='catgory',
        ),
        migrations.AddField(
            model_name='achievements',
            name='rubies_collected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='rubies_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='total_rubies_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
