# Generated by Django 4.2.20 on 2025-06-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0021_remove_changelog_model_alter_changelog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='tier',
            field=models.ForeignKey(blank=True, default='F', null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.tier'),
        ),
    ]
