# Generated by Django 4.2.20 on 2025-06-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_alter_profiledetails_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='currencyorderprice',
            field=models.IntegerField(default=0, verbose_name='Currency order price'),
        ),
    ]
