# Generated by Django 4.1.10 on 2025-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_alter_defaultavatar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number',
            field=models.IntegerField(blank=True, default=1, help_text='Position ordered by value (from highest to lowest)', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='total_number',
            field=models.IntegerField(blank=True, default=1, help_text='Position ordered by value (from highest to lowest)', null=True),
        ),
    ]
