# Generated by Django 4.1.10 on 2024-07-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_alter_choice_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffler',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
