# Generated by Django 4.1.10 on 2024-01-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_remove_choice_prize_alter_prizepool_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizepool',
            name='prize',
        ),
        migrations.AddField(
            model_name='prizepool',
            name='prize_name',
            field=models.CharField(default=1, max_length=500, verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prizepool',
            name='prizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.choice'),
        ),
    ]
