# Generated by Django 5.1.6 on 2025-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_individualcheststatistics_totalcheststatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypreferences',
            options={'verbose_name': 'My Preference'},
        ),
        migrations.AddField(
            model_name='individualcheststatistics',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active order?'),
        ),
        migrations.AddField(
            model_name='totalcheststatistics',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this an active order?'),
        ),
    ]
