# Generated by Django 4.1.10 on 2024-08-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_rename_tier_achievements_catgory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='times_subtract_called',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='total_currency_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='total_currency_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
