# Generated by Django 4.1.10 on 2025-03-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_game_number_game_total_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_number',
        ),
        migrations.AddField(
            model_name='gamechoice',
            name='number',
            field=models.IntegerField(blank=True, default=1, help_text='Position ordered by value (from highest to lowest)', null=True),
        ),
        migrations.AddField(
            model_name='gamechoice',
            name='total_number',
            field=models.IntegerField(blank=True, default=1, help_text='Position ordered by value (from highest to lowest)', null=True),
        ),
    ]
