# Generated by Django 4.1.10 on 2024-01-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_remove_prizepool_prize_prizepool_prize_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepool',
            name='image',
            field=models.FileField(default=1, upload_to='images/', verbose_name='Prize Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prizepool',
            name='prize_name',
            field=models.CharField(max_length=500, verbose_name='Prize Name'),
        ),
    ]
