# Generated by Django 4.2.20 on 2025-06-04 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0023_alter_orderitem_currencyorderprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('currency_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.currencymarket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency_market')},
            },
        ),
    ]
