# Generated by Django 5.1.6 on 2025-04-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_alter_mypreferences_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualcheststatistics',
            old_name='chests',
            new_name='chest',
        ),
    ]
