# Generated by Django 3.1.5 on 2022-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_auto_20211231_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here. If you wish to stay anonymous, put "Anonymous".', max_length=100)),
                ('position', models.CharField(help_text='Please let us know what staff position you serve currently.', max_length=200)),
                ('description', models.TextField(help_text='Write whatever you want on your profile here (within regulations).')),
                ('staff_feats', models.TextField(help_text='Let us know of your transcendental feats of making MegaClan a better place.')),
                ('image', models.FileField(help_text='Please provide a cover image for your profile.', upload_to='')),
            ],
        ),
    ]
