# Generated by Django 4.2.20 on 2025-06-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_favoritecurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='robots',
        ),
        migrations.AddField(
            model_name='robot',
            name='battle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.battle'),
            preserve_default=False,
        ),
    ]
