# Generated by Django 4.1.10 on 2024-01-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_prizepool_image_alter_prizepool_prize_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizepool',
            name='prizes',
        ),
        migrations.AddField(
            model_name='choice',
            name='prizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.prizepool'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='category',
            field=models.CharField(help_text='Category of choice (Pokemon, trainers, etc.).', max_length=100),
        ),
    ]
