# Generated by Django 5.1.6 on 2025-04-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_rename_chests_individualcheststatistics_chest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualcheststatistics',
            options={'verbose_name': 'Individual Chest Statistic'},
        ),
        migrations.AlterModelOptions(
            name='totalcheststatistics',
            options={'verbose_name': 'Total Chest Statistic'},
        ),
    ]
