# Generated by Django 4.1.10 on 2024-12-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_alter_level_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
