# Generated by Django 4.1.10 on 2024-08-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_outcome_black_counter_outcome_gold_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='black_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='gold_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='green_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='orange_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='red_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='redgold_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='yellow_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
