# Generated by Django 4.2.20 on 2025-06-16 00:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0024_favoritecurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='robots',
        ),
        migrations.AddField(
            model_name='event',
            name='length',
            field=models.DurationField(default=datetime.timedelta(days=7), help_text='Duration of the event; defaults to 7 days', verbose_name='Event duration'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='total_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='battleparticipant',
            name='battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='showcase.battle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Time and date of Event Creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='numeric_quantifier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='page',
            field=models.TextField(blank=True, null=True, verbose_name='Page Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='qualitative_qualifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='host'),
        ),
    ]
