# Generated by Django 4.1.2 on 2023-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0024_remove_item_hyperlink_alter_feedback_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='hyperlink',
            field=models.CharField(default=1, help_text='Leave field blank, hyperlink will automatically fill with the link to the associated product.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(default=1, help_text='Leave blank to use corresponding product slug.', max_length=200),
            preserve_default=False,
        ),
    ]
