# Generated by Django 4.2.20 on 2025-08-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0025_remove_battle_participants_remove_battle_robots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementbase',
            name='advertisement',
            field=models.ImageField(blank=True, height_field='advertisement_width', help_text='Image of the advertisement.', null=True, upload_to='images/', width_field='advertisement_length'),
        ),
        migrations.AlterField(
            model_name='advertisementbase',
            name='advertisement_hyperlink',
            field=models.TextField(blank=True, null=True, verbose_name='Hyperlink'),
        ),
        migrations.AlterField(
            model_name='advertisementbase',
            name='advertisement_position',
            field=models.IntegerField(default=0, help_text='Positioning of the advertisement.', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='advertisementbase',
            name='type',
            field=models.CharField(blank=True, help_text='Type of product.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementbase',
            name='xposition',
            field=models.IntegerField(default=0, help_text='x-position.', verbose_name='x-position'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.tier'),
        ),
    ]
