# Generated by Django 4.1.10 on 2024-01-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0025_remove_prizepool_prizes_choice_prizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizepool',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AddField(
            model_name='prizepool',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Number of Prize'),
        ),
    ]
