# Generated by Django 4.1.10 on 2024-12-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0025_alter_level_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
