# Generated by Django 4.1.10 on 2024-07-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0025_alter_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_currency_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
