# Generated by Django 4.2.20 on 2025-06-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0025_remove_battle_participants_remove_battle_robots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='battle',
        ),
        migrations.AddField(
            model_name='robot',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='battleparticipant',
            name='battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='showcase.battle'),
        ),
    ]
