# Generated by Django 3.1.5 on 2022-01-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0026_auto_20220101_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='staff_feats',
        ),
    ]
