# Generated by Django 4.1.10 on 2024-12-14 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0026_alter_level_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.profiledetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
