# Generated by Django 4.2.20 on 2025-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0026_alter_advertisementbase_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecarousel',
            name='specialty',
            field=models.CharField(blank=True, choices=[('F', 'Featured'), ('N', 'New'), ('P', 'Popular'), ('PR', 'Premium'), ('LE', 'Limited Edition')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='specialty',
            field=models.CharField(blank=True, choices=[('F', 'Featured'), ('N', 'New'), ('P', 'Popular'), ('PR', 'Premium'), ('LE', 'Limited Edition')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='specialty',
            field=models.CharField(blank=True, choices=[('F', 'Featured'), ('N', 'New'), ('P', 'Popular'), ('PR', 'Premium'), ('LE', 'Limited Edition')], max_length=2, null=True),
        ),
    ]
