# Generated by Django 4.1.10 on 2024-07-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0026_item_discount_currency_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_currency_based',
            field=models.BooleanField(default=False),
        ),
    ]
