# Generated by Django 4.1.10 on 2024-08-27 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0026_remove_achievements_catgory_achievements_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={'verbose_name': 'Withdrawal Card', 'verbose_name_plural': 'Withdrawal Cards'},
        ),
        migrations.AlterField(
            model_name='inventoryobject',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='currency_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WithdrawClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cards', models.IntegerField(blank=True, null=True)),
                ('shipping_state', models.CharField(choices=[('P', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered'), ('R', 'Refunded'), ('C', 'Canceled'), ('D', 'Damaged In Transit'), ('O', 'On Hold')], default='S', max_length=1)),
                ('open', models.BooleanField(default=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('date_and_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time and date')),
                ('status', models.CharField(choices=[('P', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered'), ('R', 'Refunded'), ('C', 'Canceled'), ('D', 'Damaged In Transit'), ('O', 'On Hold')], default='P', max_length=1)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Is this withdraw active?')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('withdraw', models.ManyToManyField(to='showcase.withdraw')),
            ],
        ),
    ]
