# Generated by Django 4.1.10 on 2024-07-16 16:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0027_item_is_currency_based'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='nonce', unique=True),
            preserve_default=False,
        ),
    ]
