# Generated by Django 4.1.2 on 2023-07-09 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0027_remove_item_hyperlink_message_signed_in_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='signed_in_user',
        ),
        migrations.AddField(
            model_name='item',
            name='hyperlink',
            field=models.TextField(blank=True, help_text='Feedbacks will use this hyperlink as a link to this product.', null=True, verbose_name='Hyperlink'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='hyperlink',
            field=models.CharField(blank=True, help_text='Leave field blank, hyperlink will automatically fill with the link to the associated product.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to use corresponding product slug.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=1000000),
        ),
    ]
