# Generated by Django 4.1.10 on 2024-01-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0027_remove_shuffler_choices_shuffler_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffler',
            name='choices',
            field=models.ManyToManyField(blank=True, to='showcase.choice'),
        ),
    ]
