# Generated by Django 4.1.10 on 2024-12-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0027_experience_profile_alter_experience_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='experience',
            new_name='earned_experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='level',
            field=models.ManyToManyField(to='showcase.level'),
        ),
    ]
