# Generated by Django 4.1.10 on 2024-01-19 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0028_alter_shuffler_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='nonce',
        ),
        migrations.AddField(
            model_name='choice',
            name='lower_nonce',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Lower bound nonce of Choice', max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='choice',
            name='upper_nonce',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Upper bound nonce of Choice', max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
