# Generated by Django 4.1.10 on 2024-07-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0028_alter_outcome_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='image_length',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width'),
        ),
    ]
