# Generated by Django 4.1.10 on 2024-12-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0028_rename_experience_level_earned_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='earned_experience',
            new_name='experience',
        ),
        migrations.AlterField(
            model_name='experience',
            name='level',
            field=models.ManyToManyField(related_name='current_level', to='showcase.level'),
        ),
    ]
