# Generated by Django 4.1.10 on 2024-01-20 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import showcase.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0029_remove_choice_nonce_choice_lower_nonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rubiaces', max_length=200)),
                ('flavor_text', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Sprite')),
                ('image_length', models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length')),
                ('image_width', models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width')),
                ('mfg_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Lottery',
                'verbose_name_plural': 'Lotteries',
            },
        ),
        migrations.CreateModel(
            name='LotteryTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Daily Lotto', max_length=200)),
                ('flavor_text', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Sprite')),
                ('lottery_number', models.CharField(default=showcase.models.create_unique_lottery_number, max_length=10, unique=True)),
                ('image_length', models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length')),
                ('image_width', models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width')),
                ('mfg_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lottery Ticket',
                'verbose_name_plural': 'Lottery Ticket',
            },
        ),
    ]
