# Generated by Django 4.1.10 on 2024-07-21 00:41

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0030_alter_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinnerChoiceRenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nonce', unique=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('ratio', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_length', models.PositiveIntegerField(blank=True, default=100, help_text='Original length of the advertisement (use for original ratio).', null=True, verbose_name='image length')),
                ('image_width', models.PositiveIntegerField(blank=True, default=100, help_text='Original width of the advertisement (use for original ratio).', null=True, verbose_name='image width')),
                ('color', models.CharField(blank=True, choices=[('Gra', 'Gray'), ('Gre', 'Green'), ('Y', 'Yellow'), ('O', 'Orange'), ('R', 'Red'), ('B', 'Black'), ('G', 'Gold')], max_length=3, null=True)),
                ('nonce', models.DecimalField(decimal_places=0, max_digits=6)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.choice')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.game')),
                ('game_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_creator', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.gamehub')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
