# Generated by Django 4.1.10 on 2024-01-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0030_lottery_lotterytickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='tickets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.lotterytickets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lottery',
            name='name',
            field=models.CharField(default='Daily Lotto', max_length=200),
        ),
    ]
