# Generated by Django 4.1.10 on 2024-01-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0031_lottery_tickets_alter_lottery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='tickets',
        ),
        migrations.AddField(
            model_name='lottery',
            name='tickets',
            field=models.ManyToManyField(related_name='lotteries', to='showcase.lotterytickets'),
        ),
    ]
