# Generated by Django 4.1.10 on 2024-07-22 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0032_choice_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='generated_nonce',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Do NOT fill out manually.', max_digits=7, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
