# Generated by Django 4.1.10 on 2024-01-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0032_remove_lottery_tickets_lottery_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotterytickets',
            options={'verbose_name': 'Lottery Ticket', 'verbose_name_plural': 'Lottery Tickets'},
        ),
    ]
