# Generated by Django 4.1.10 on 2024-12-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0032_alter_experience_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
