# Generated by Django 4.1.10 on 2024-12-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0033_alter_experience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='full_row',
            field=models.BooleanField(default=True),
        ),
    ]
