# Generated by Django 4.1.10 on 2024-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0034_alter_choice_generated_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='image',
        ),
        migrations.AddField(
            model_name='outcome',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
