# Generated by Django 4.1.10 on 2024-12-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0034_level_full_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='games',
            field=models.ManyToManyField(blank=True, limit_choices_to={'daily': True}, related_name='levels', to='showcase.game', verbose_name='Games with Daily Mode'),
        ),
    ]
