# Generated by Django 4.1.10 on 2024-01-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0034_remove_choice_question_pollquestion_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='tickets',
        ),
        migrations.AddField(
            model_name='lotterytickets',
            name='lottery',
            field=models.ManyToManyField(related_name='lotteries', to='showcase.lottery'),
        ),
    ]
