# Generated by Django 4.1.10 on 2024-01-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0035_remove_lottery_tickets_lotterytickets_lottery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotterytickets',
            name='lottery',
        ),
        migrations.AddField(
            model_name='lotterytickets',
            name='lottery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.lottery'),
            preserve_default=False,
        ),
    ]
