# Generated by Django 4.1.10 on 2024-12-15 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0035_game_daily_level_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='unlocking_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.level'),
        ),
    ]
