# Generated by Django 4.1.10 on 2024-07-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0036_spinnerchoicerenders_lower_nonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_avatar_name', models.CharField(max_length=300)),
                ('default_avatar', models.ImageField(upload_to='')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
            options={
                'verbose_name': 'Default Avatar',
                'verbose_name_plural': 'Default Avatars',
            },
        ),
        migrations.AddField(
            model_name='respondingtradeoffer',
            name='trade_offer_exists',
            field=models.BooleanField(default=False, help_text='Indicates if the trade has been completed previously.'),
        ),
    ]
