# Generated by Django 4.1.10 on 2024-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0036_remove_lotterytickets_lottery_lotterytickets_lottery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterytickets',
            name='flavor_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
