# Generated by Django 4.1.10 on 2024-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0036_spinnerchoicerenders_lower_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondingtradeoffer',
            name='trade_offer_exists',
            field=models.BooleanField(default=False, help_text='Indicates if the trade has been completed previously.'),
        ),
    ]
