# Generated by Django 4.1.10 on 2024-12-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0037_alter_game_unlocking_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='unlocking_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.level'),
        ),
    ]
