# Generated by Django 4.1.10 on 2024-01-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0037_alter_lotterytickets_flavor_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='profile_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
