# Generated by Django 4.1.10 on 2024-03-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0038_friend_last_messaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_username',
            field=models.CharField(max_length=500, blank=True, null=True),
        ),
    ]
