# Generated by Django 4.1.10 on 2024-12-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0038_alter_game_unlocking_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lottery',
            name='price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
