# Generated by Django 4.1.10 on 2024-01-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0040_lottery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='slug',
        ),
    ]
