# Generated by Django 4.1.10 on 2024-12-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0040_alter_lottery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='maximum_tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
        ),
    ]
