# Generated by Django 4.1.10 on 2024-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0041_lottery_maximum_tickets_alter_lottery_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cooldown',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
