# Generated by Django 3.1.5 on 2022-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0044_auto_20220119_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
    ]
