# Generated by Django 4.1.10 on 2024-12-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0044_affiliation_alter_level_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='unlocking_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_to_unlock', to='showcase.level'),
        ),
    ]
