# Generated by Django 4.1.10 on 2024-01-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0044_profiledetails_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='user',
        ),
        migrations.AddField(
            model_name='level',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
        migrations.AddField(
            model_name='level',
            name='level_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
