# Generated by Django 3.1.5 on 2022-01-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0045_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Sold_out', null=True),
        ),
    ]
