# Generated by Django 4.1.10 on 2024-01-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0045_remove_level_user_level_is_active_level_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.subscription'),
        ),
    ]
