# Generated by Django 4.1.10 on 2024-01-28 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0046_alter_profiledetails_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['level'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='showcase.level'),
        ),
    ]
