# Generated by Django 4.1.10 on 2024-01-28 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0047_alter_level_options_alter_profiledetails_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuffler',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shuffler',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='currency_amount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
