# Generated by Django 4.1.10 on 2024-12-17 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0047_ascension_delete_ascention'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cooldown')},
            },
        ),
    ]
