# Generated by Django 4.1.10 on 2024-12-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0048_dailyspin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='unlocked_daily_chests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.game'),
        ),
    ]
