# Generated by Django 3.1.5 on 2022-01-20 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0048_auto_20220119_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutaddress',
            options={'verbose_name_plural': 'Checkout Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
    ]
