# Generated by Django 4.1.10 on 2024-01-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0049_currencymarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymarket',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
