# Generated by Django 4.1.10 on 2024-01-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0050_currencymarket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencymarket',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='currencymarket',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
