# Generated by Django 4.1.10 on 2024-01-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0051_rename_cost_currencymarket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymarket',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
