# Generated by Django 3.2.11 on 2022-01-22 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0052_profiletwo_publicprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('city', models.CharField(max_length=30)),
                ('fullname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PublicProfile',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='r',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showcase.user'),
        ),
        migrations.AlterField(
            model_name='profiletwo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showcase.user'),
        ),
    ]
