# Generated by Django 4.1.10 on 2024-12-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0053_ascension_profile_ascension_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascension',
            name='final_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='necessary_level_to_unlock', to='showcase.level'),
        ),
    ]
