# Generated by Django 4.1.10 on 2024-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0054_currencyorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyorder',
            name='feedback_url',
        ),
        migrations.AddField(
            model_name='currencyorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
