# Generated by Django 4.1.10 on 2024-12-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0054_alter_ascension_final_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascension',
            name='ascension',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
