# Generated by Django 4.1.10 on 2024-12-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0055_alter_ascension_ascension'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascension',
            name='ascension_number',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
