# Generated by Django 4.1.10 on 2024-01-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0055_remove_currencyorder_feedback_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymarket',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
