# Generated by Django 4.1.10 on 2024-01-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0056_currencymarket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyorder',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
