# Generated by Django 4.1.10 on 2024-12-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0056_ascension_ascension_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascension',
            name='flavor_text',
            field=models.CharField(blank=True, choices=[('A', 'Ate the forbidden cookies'), ('B', 'Bit the bullet'), ('C', 'Caught in the act'), ('D', "Doordash'd "), ('E', 'Enigma '), ('S', 'Shacked to a galloping horse'), ('X', 'Xyster to the keister'), ('Z', 'Zapperdoodled')], max_length=1, null=True),
        ),
    ]
