# Generated by Django 4.1.10 on 2024-12-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0057_alter_ascension_flavor_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='demonstration',
            field=models.BooleanField(default=False),
        ),
    ]
