# Generated by Django 4.1.10 on 2024-01-30 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0057_currencyorder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='seller',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('identification', models.FileField(help_text="Please provide a valid government-issued id (Passport, Driver's License, Birth Certificate, etc", upload_to='')),
                ('mobile_number', models.CharField(help_text='Please include area code', max_length=10, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Seller Application',
                'verbose_name_plural': 'Seller Applications',
            },
        ),
    ]
