# Generated by Django 4.1.10 on 2024-12-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0058_game_demonstration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='demonstration',
        ),
        migrations.AddField(
            model_name='outcome',
            name='demonstration',
            field=models.BooleanField(default=False),
        ),
    ]
