# Generated by Django 4.1.10 on 2024-12-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0059_remove_game_demonstration_outcome_demonstration'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstrosity',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showcase.currency'),
            preserve_default=False,
        ),
    ]
