# Generated by Django 4.1.10 on 2024-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0060_alter_sellerapplication_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
