# Generated by Django 4.1.10 on 2024-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0060_monstrosity_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstrosity',
            name='currency_amount',
            field=models.IntegerField(default=0),
        ),
    ]
