# Generated by Django 4.1.10 on 2024-12-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0061_monstrosity_currency_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstrosity',
            name='feed_amount',
            field=models.IntegerField(default=0),
        ),
    ]
