# Generated by Django 4.1.10 on 2024-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0061_sellerapplication_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplication',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='sellerapplication',
            name='phone_verified',
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='email',
            field=models.CharField(default=1, help_text='Please input your email', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
