# Generated by Django 4.1.10 on 2024-01-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0062_remove_sellerapplication_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='email',
            field=models.EmailField(help_text='Please input your email', max_length=10, unique=True),
        ),
    ]
