# Generated by Django 4.1.10 on 2024-12-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0062_monstrosity_feed_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.currency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.profiledetails')),
            ],
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='other_currencies_amount',
            field=models.ManyToManyField(related_name='profile_currencies', through='showcase.ProfileCurrency', to='showcase.currency'),
        ),
    ]
