# Generated by Django 4.1.10 on 2024-01-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0063_alter_sellerapplication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='email',
            field=models.EmailField(help_text='Please input your email', max_length=254, unique=True),
        ),
    ]
