# Generated by Django 4.1.10 on 2024-12-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0063_profilecurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmessage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
