# Generated by Django 4.1.10 on 2024-12-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0064_alter_generalmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
