# Generated by Django 4.1.10 on 2024-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0064_alter_sellerapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
