# Generated by Django 4.1.10 on 2024-01-31 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0065_sellerapplication_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfield',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='identification',
            field=models.FileField(help_text="Please provide a valid government-issued id (Passport, Driver's License, Birth Certificate, etc)", upload_to=''),
        ),
    ]
