# Generated by Django 4.1.10 on 2024-12-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0065_alter_generalmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
            preserve_default=False,
        ),
    ]

