# Generated by Django 4.1.10 on 2024-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0067_prizepool_currency_prizepool_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeprize',
            old_name='prize',
            new_name='choice_text',
        ),
        migrations.AddField(
            model_name='exchangeprize',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
