# Generated by Django 4.1.10 on 2024-12-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0069_rename_choice_text_exchangeprize_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
