# Generated by Django 4.1.10 on 2025-01-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0072_battleparticipant_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='notifications_status',
            field=models.CharField(choices=[('ON', 'Online'), ('DND', 'Do Not Disturb'), ('OFF', 'Offline')], default='OFF', max_length=3),
        ),
    ]
