# Generated by Django 4.1.10 on 2025-01-07 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0075_remove_notification_is_read_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
