# Generated by Django 4.1.10 on 2025-01-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0076_notification_user_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytradeoffer',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
    ]
