# Generated by Django 3.2.11 on 2022-07-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0076_alter_item_relateditems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'verbose_name': 'Background Image', 'verbose_name_plural': 'Background Images'},
        ),
        migrations.AlterField(
            model_name='item',
            name='relateditems',
            field=models.ManyToManyField(blank=True, related_name='_showcase_item_relateditems_+', to='showcase.Item'),
        ),
    ]
