# Generated by Django 4.1.10 on 2025-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0077_inventorytradeoffer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytradeoffer',
            options={'verbose_name': 'Inventory Trade Offer'},
        ),
        migrations.AddConstraint(
            model_name='inventorytradeoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('initiator', 'receiver', 'status'), name='unique_pending_trades'),
        ),
    ]
