# Generated by Django 3.2.11 on 2022-07-14 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0077_auto_20220713_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
