# Generated by Django 4.1.10 on 2025-01-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0078_alter_inventorytradeoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'verbose_name': 'User Notification'},
        ),
        migrations.AddField(
            model_name='inventorytradeoffer',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
