# Generated by Django 4.1.10 on 2025-01-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0079_alter_usernotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfield',
            name='email',
            field=models.EmailField(help_text='Sign up for our newsletter to get the latest news and gossip! We will never share your personal information with anyone without your explicit permission. Unsubscribe at any time.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='length_for_resize',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Resized Length'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='width_for_resize',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Resized Width'),
        ),
    ]
