# Generated by Django 3.2.11 on 2022-08-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0080_ebackgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.URLField(help_text='Upload a background image for the cover page.'),
        ),
    ]
