# Generated by Django 4.1.10 on 2025-01-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0080_alter_emailfield_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='difficulty',
            field=models.CharField(choices=[('M', 'Mild'), ('S', 'Spicy'), ('F', 'Fiery'), ('W', 'Wild'), ('E', 'Explosive')], default='M', max_length=1),
        ),
    ]
