# Generated by Django 4.1.10 on 2025-01-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0081_achievements_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='identification',
            field=models.FileField(help_text="Please provide a valid government-issued ID (Passport, Driver's License, Birth Certificate, etc)", upload_to=''),
        ),
    ]
