# Generated by Django 3.2.11 on 2022-08-23 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0082_auto_20220811_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebackgroundimage',
            options={'verbose_name': 'Background Image', 'verbose_name_plural': 'Background Images'},
        ),
        migrations.RemoveField(
            model_name='ebackgroundimage',
            name='image',
        ),
        migrations.AddField(
            model_name='ebackgroundimage',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebackgroundimage',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
