# Generated by Django 4.1.10 on 2025-01-12 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0082_alter_sellerapplication_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='inventoryobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showcase.inventoryobject'),
        ),
    ]
