# Generated by Django 3.2.11 on 2022-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0083_auto_20220823_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilletBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Billet Background Image',
                'verbose_name_plural': 'Billet Background Images',
            },
        ),
        migrations.AlterModelOptions(
            name='ebackgroundimage',
            options={'verbose_name': 'Ecommerce Background Image', 'verbose_name_plural': 'Ecommerce Background Images'},
        ),
    ]
