# Generated by Django 4.1.10 on 2025-01-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0084_alter_game_cost_tophits'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='slag',
            field=models.SlugField(unique=True, blank=True, max_length=16, null=True),
        ),
    ]
