# Generated by Django 3.2.11 on 2022-10-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0084_auto_20220825_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Ecommerce Background Image',
                'verbose_name_plural': 'Ecommerce Background Images',
            },
        ),
    ]
