# Generated by Django 4.1.10 on 2025-01-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0085_withdraw_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='slag',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
