# Generated by Django 4.1.10 on 2025-01-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0086_alter_withdraw_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile2',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile2',
            name='zip_code',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='shipping_state',
            field=models.CharField(choices=[('P', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered'), ('R', 'Refunded'), ('C', 'Canceled'), ('D', 'Damaged In Transit'), ('O', 'On Hold')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('E', 'Earlier Than Expected'), ('O', 'On Time'), ('L', 'Late'), ('N', 'Not Applicable - Down'), ('N', 'Not Applicable - Intended')], default='P', max_length=1),
        ),
    ]
