# Generated by Django 4.1.10 on 2025-01-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0087_alter_userprofile2_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', 1)), fields=('user', 'is_active'), name='unique_active_address_per_user'),
        ),
    ]
