# Generated by Django 4.1.10 on 2025-01-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0088_alter_address_apartment_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_active_address_per_user',
        ),
    ]
