# Generated by Django 4.1.10 on 2025-01-15 06:28

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0089_remove_address_unique_active_address_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Saved Addresses'},
        ),
        migrations.AddField(
            model_name='userprofile2',
            name='country',
            field=django_countries.fields.CountryField(default='United States of America', max_length=2),
        ),
    ]
