# Generated by Django 4.1.10 on 2023-09-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0089_message_message_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofile',
            name='profile_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
