# Generated by Django 4.1.2 on 2022-11-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0089_rename_settings_settingsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Settings Background Image',
                'verbose_name_plural': 'Settings Background Images',
            },
        ),
    ]
