# Generated by Django 4.1.10 on 2025-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0090_alter_address_options_userprofile2_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
