# Generated by Django 4.1.2 on 2022-11-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0090_settingsbackgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Your username', max_length=200)),
                ('password', models.CharField(help_text='Your password', max_length=200)),
                ('coupons', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Send me coupons')),
                ('news', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Keep me in the loop')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.DeleteModel(
            name='ImageCarousel',
        ),
        migrations.DeleteModel(
            name='SettingsBackgroundImage',
        ),
        migrations.DeleteModel(
            name='SettingsModel',
        ),
        migrations.AlterField(
            model_name='backgroundimagebase',
            name='position',
            field=models.IntegerField(verbose_name='Positioning of Image'),
        ),
    ]
