# Generated by Django 4.1.10 on 2025-01-17 06:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0091_level_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
