# Generated by Django 4.1.10 on 2025-01-17 07:32

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0092_level_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color_wheel',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
        migrations.AlterField(
            model_name='level',
            name='color',
            field=models.CharField(blank=True, help_text='Comma-separated hex colors for gradient', max_length=500, null=True),
        ),
    ]
