# Generated by Django 4.1.10 on 2023-09-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0092_alter_updateprofile_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='profile_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
