# Generated by Django 4.1.10 on 2025-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0093_level_color_wheel_alter_level_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
