# Generated by Django 4.1.2 on 2022-11-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0094_logobase_alternate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanAppealBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Ban Appliciations Background Image',
                'verbose_name_plural': 'Ban Applications Background Images',
            },
        ),
        migrations.CreateModel(
            name='PunishAppsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Punishment Applications Background Image',
                'verbose_name_plural': 'Punishment Applications Background Images',
            },
        ),
        migrations.CreateModel(
            name='SupportBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Support Background Image',
                'verbose_name_plural': 'Support Background Images',
            },
        ),
        migrations.RemoveField(
            model_name='basecopyrighttextfield',
            name='text',
        ),
        migrations.AddField(
            model_name='basecopyrighttextfield',
            name='copyright',
            field=models.TextField(default=1, help_text='Copyright And Year', verbose_name='Copyright Field'),
            preserve_default=False,
        ),
    ]
