# Generated by Django 4.1.10 on 2025-01-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0094_alter_battle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
