# Generated by Django 5.0 on 2025-01-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0096_inventory_number_of_cards_alter_level_color_wheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='card_category',
            field=models.CharField(choices=[('P', 'Pokemon'), ('M', 'Magic The Gathering'), ('B', 'Bakugo'), ('Y', 'Yu-Gi-Oh!'), ('A', 'Anime'), ('O', 'Other')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('D', 'Damaged')], default='M', max_length=2, null=True),
        ),
    ]
