# Generated by Django 4.1.2 on 2022-11-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0096_basecopyrighttextfield_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logobase',
            old_name='cover',
            new_name='logocover',
        ),
        migrations.AlterField(
            model_name='faviconbase',
            name='favicontype',
            field=models.TextField(help_text='example: ico', verbose_name='Favicon Type'),
        ),
    ]
