# Generated by Django 5.0 on 2025-01-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0097_inventory_number_of_cards_item_card_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='trader',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
