# Generated by Django 5.0 on 2025-01-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0098_inventory_number_of_cards_profiledetails_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='partner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
