# Generated by Django 4.1.2 on 2022-11-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0099_advertisementpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Advertisement title.', max_length=100)),
                ('image', models.ImageField(help_text='Image of the advertisement.', upload_to='')),
                ('position', models.IntegerField(help_text='Positioning of the advertisement.')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('advertisement_width', models.IntegerField(help_text='Width of the advertisement (in percent relative).', verbose_name='advertisement width')),
                ('advertisement_length', models.IntegerField(help_text='Length of the advertisement (in percent relative).', verbose_name='advertisement length')),
                ('xposition', models.IntegerField(help_text='x-position.', verbose_name='x-position')),
                ('yposition', models.IntegerField(help_text='x-position.', verbose_name='y-position')),
                ('relevance', models.TextField(help_text='Relevance of advertisement')),
                ('type', models.CharField(help_text='Type of product.', max_length=200)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('correlating_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.item')),
            ],
            options={
                'verbose_name': 'Image Carousel Post',
                'verbose_name_plural': 'Image Carousel Posts',
            },
        ),
        migrations.DeleteModel(
            name='AdvertisementPost',
        ),
    ]
