# Generated by Django 5.0 on 2025-02-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0099_inventory_number_of_cards_profiledetails_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='gamechoices', to='showcase.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_fk_set', to='showcase.game'),
        ),
    ]
