# Generated by Django 5.0 on 2025-02-04 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0100_game_choices_inventory_number_of_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='generated_nonce',
            field=models.IntegerField(blank=True, help_text='Do NOT fill out manually.', null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Generated Nonce'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='lower_nonce',
            field=models.IntegerField(blank=True, help_text='Lower bound nonce of Choice', null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='upper_nonce',
            field=models.IntegerField(blank=True, help_text='Upper bound nonce of Choice', null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
