# Generated by Django 5.0 on 2025-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0101_inventory_number_of_cards_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Pokemon'), ('M', 'Magic The Gathering'), ('B', 'Bakugo'), ('Y', 'Yu-Gi-Oh!'), ('A', 'Anime'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='number_of_choice',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Pokemon'), ('M', 'Magic The Gathering'), ('B', 'Bakugo'), ('Y', 'Yu-Gi-Oh!'), ('A', 'Anime'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
