# Generated by Django 5.0 on 2025-02-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0102_inventory_number_of_cards_alter_choice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='number_of_choice',
            field=models.IntegerField(default=1),
        ),
    ]
