# Generated by Django 5.0 on 2025-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0103_inventory_number_of_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='official_items', to='showcase.prizepool'),
        ),
    ]
