# Generated by Django 5.0 on 2025-02-07 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0105_inventory_number_of_cards_votequery_delete_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('vote_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='showcase.votequery')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.votequery')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.voteoption')),
            ],
            options={
                'unique_together': {('user', 'vote_query')},
            },
        ),
    ]
