# Generated by Django 5.0 on 2025-02-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0106_inventory_number_of_cards_voteoption_ballot'),
    ]

    operations = [
        migrations.AddField(
            model_name='endowment',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
    ]
