# Generated by Django 4.1.2 on 2022-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0106_rename_image_imagecarousel_carouselimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecarousel',
            name='position',
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='carouselposition',
            field=models.IntegerField(default=1, help_text='Positioning of the image within the carousel.', verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='carouseltotal',
            field=models.IntegerField(default=1, help_text='Total number of images within the carousel.', verbose_name='total images'),
            preserve_default=False,
        ),
    ]
