# Generated by Django 5.0 on 2025-02-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0107_endowment_is_active_inventory_number_of_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='usd', max_length=3),
        ),
    ]
