# Generated by Django 4.1.2 on 2022-11-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0108_alter_imagecarousel_carouselimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecarousel',
            old_name='page',
            new_name='carouselpage',
        ),
        migrations.AlterField(
            model_name='imagecarousel',
            name='carouselimage',
            field=models.ImageField(help_text='Link a URL for your profile (scales to your picture`s dimensions.)', upload_to='images/', verbose_name='image'),
        ),
    ]
