# Generated by Django 5.0 on 2025-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0108_currency_code_inventory_number_of_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('free for all', 'Free For All'), ('Upside-Down', 'Upside-Down'), ('Teams', 'Teams'), ('Dual_Win', 'Dual Win'), ('Team_Fight', 'Team Fight'), ('Do_Not_Lose', 'Do Not Lose'), ('Share', 'Share')], default='free_for_all', max_length=20),
        ),
    ]
