# Generated by Django 5.0 on 2025-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0109_inventory_number_of_cards_alter_battle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('free_for_all', 'Free For All'), ('upside_down', 'Upside-Down'), ('teams', 'Teams'), ('dual_win', 'Dual Win'), ('team_fight', 'Team Fight'), ('do_not_lose', 'Do Not Lose'), ('share', 'Share')], default='free_for_all', max_length=20),
        ),
    ]
