# Generated by Django 5.0 on 2025-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0111_inventory_number_of_cards_alter_battle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('Free For All', 'Free For All'), ('upside_down', 'Upside-Down'), ('teams', 'Teams'), ('dual_win', 'Dual Win'), ('team_fight', 'Team Fight'), ('do_not_lose', 'Do Not Lose'), ('share', 'Share')], default='Free For All', max_length=20),
        ),
    ]
