# Generated by Django 4.1.2 on 2022-12-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0111_perksbackgroundimage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Change Password Background Image',
                'verbose_name_plural': 'Change Password Background Images',
            },
        ),
        migrations.CreateModel(
            name='CheckoutBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Checkout Background Image',
                'verbose_name_plural': 'Checkout Background Images',
            },
        ),
        migrations.CreateModel(
            name='IssueBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Issue Background Image',
                'verbose_name_plural': 'Issue Background Images',
            },
        ),
        migrations.CreateModel(
            name='ReasonsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Reasons Background Image',
                'verbose_name_plural': 'Reasons Background Images',
            },
        ),
        migrations.CreateModel(
            name='SignupBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Signup Background Image',
                'verbose_name_plural': 'SignupBackground Images',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on: '),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(null=True, verbose_name='time and date'),
        ),
        migrations.AlterField(
            model_name='punishappeal',
            name='Additional_comments',
            field=models.TextField(help_text='Put any additional evidence or comments you may have here.', verbose_name='additional comments '),
        ),
        migrations.AlterField(
            model_name='punishappeal',
            name='Rule_broken',
            field=models.CharField(help_text='Tell us the numbers of the rule(s) you broke. Refer to our rules page to see the rules and their corresponding numbers.', max_length=200, verbose_name='rule broken: '),
        ),
        migrations.AlterField(
            model_name='punishappeal',
            name='Why_I_should_have_my_punishment_revoked',
            field=models.TextField(help_text='Tell us why we should revoke your punishment, and what you can do to fix your mistake. If you think your punishment is a mistake, tell us why.', verbose_name='Why I should have my punishment revoked: '),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='Additional_comments',
            field=models.TextField(help_text='Put any additional comments you may have here.', verbose_name='additional comments'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_feats',
            field=models.TextField(help_text='Let us know of your transcendental feats of making MegaClan a better place.', verbose_name='staff feats'),
        ),
        migrations.AlterField(
            model_name='support',
            name='Additional_comments',
            field=models.TextField(help_text='Put any additional comments you may have here.', verbose_name='additional comments'),
        ),
    ]
