# Generated by Django 5.0 on 2025-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0112_inventory_number_of_cards_robot_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlegame',
            options={'ordering': ['order'], 'verbose_name': 'Battle Game', 'verbose_name_plural': 'Battle Games'},
        ),
        migrations.AddField(
            model_name='battlegame',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
