# Generated by Django 5.0 on 2025-02-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0113_alter_battlegame_options_battlegame_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='game_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
