# Generated by Django 3.1.5 on 2021-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20211107_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(help_text='Please give us a picture that represents your idea. It does not have to be exact.', null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.FileField(help_text='Please give us a picture that represents your idea. It does not have to be exact.', null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='image',
            field=models.FileField(help_text='Upload a picture for your profile (scales to your picture`s dimensions.)', null=True, upload_to='gallery'),
        ),
    ]
