# Generated by Django 3.1.5 on 2021-11-11 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_auto_20211109_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_name',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='image',
            field=models.URLField(default=django.utils.timezone.now, help_text='Upload a picture for your profile (scales to your picture`s dimensions.)'),
            preserve_default=False,
        ),
    ]
