# Generated by Django 3.1.5 on 2021-12-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_staffapplications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffApplications',
            new_name='StaffApplication',
        ),
    ]
