# Generated by Django 3.1.5 on 2021-12-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_auto_20211229_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your server name goes here.', max_length=100)),
                ('category', models.CharField(help_text='Pick a category you feel your server represents (gaming, community, etc).', max_length=100)),
                ('description', models.TextField(help_text='Describe your server. Tell potential members why they should join.')),
                ('server_invite', models.FileField(help_text='Idea your server invite link here.', upload_to='')),
            ],
        ),
    ]
