# Generated by Django 3.1.5 on 2021-12-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here.', max_length=100)),
                ('Rule_broken', models.CharField(help_text='Tell us the numbers of the rule(s) you broke. Refer to our rules page to see the rules and their corresponding numbers.', max_length=200)),
                ('Why_I_should_have_my_ban_revoked', models.TextField(help_text='Tell us why we should unban you, and tell us you can do to fix your mistake. If you think your punishment is a mistake, tell us why.')),
                ('Additional_comments', models.TextField(help_text='Put any additional evidence or comments you may have here.')),
            ],
        ),
        migrations.CreateModel(
            name='PunishmentAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here.', max_length=100)),
                ('Rule_broken', models.CharField(help_text='Tell us the numbers of the rule(s) you broke. Refer to our rules page to see the rules and their corresponding numbers.', max_length=200)),
                ('Why_I_should_have_my_punishment_revoked', models.TextField(help_text='Tell us why we should revoke your punishment, and what you can do to fix your mistake. If you think your punishment is a mistake, tell us why.')),
                ('Additional_comments', models.TextField(help_text='Put any additional evidence or comments you may have here.')),
            ],
        ),
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name and tag go here. If you wish to stay anonymous, put "Anonymous".', max_length=100)),
                ('category', models.CharField(help_text='Please let us know what type of issue this is.', max_length=200)),
                ('issue', models.TextField(help_text='Describe the issue in detail. We will try to get to it as soon as possible.')),
                ('Additional_comments', models.TextField(help_text='Put any additional evidence or comments you may have here.')),
                ('image', models.FileField(help_text='Please put a screenshot of the issue.', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='poste',
            name='image',
        ),
        migrations.AlterField(
            model_name='partner',
            name='server_invite',
            field=models.URLField(help_text='Idea your server invite link here.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='Your name and tag go here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='poste',
            name='category',
            field=models.CharField(help_text='Please put your candidate here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='poste',
            name='description',
            field=models.TextField(help_text='Put any additional comments here.'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='name',
            field=models.CharField(help_text='Your name and tag go here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='name',
            field=models.CharField(help_text='Your name and tag go here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='name',
            field=models.CharField(help_text='Your name & tag go here.', max_length=100),
        ),
    ]
