# Generated by Django 3.1.5 on 2021-12-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0022_auto_20211230_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportissue',
            name='Additional_comments',
            field=models.TextField(help_text='Put any additional comments you may have here.'),
        ),
    ]
