# Generated by Django 3.1.5 on 2022-01-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0030_auto_20220104_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_on'], 'verbose_name': 'Blog Entry', 'verbose_name_plural': 'Blog Entries'},
        ),
    ]
