# Generated by Django 3.1.5 on 2022-01-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0035_checkoutaddress_item_order_orderitem_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=200)),
                ('subject', models.CharField(help_text='Subject of your message.', max_length=100)),
                ('message', models.TextField(help_text='Your message goes here.')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('G', 'Gold'), ('P', 'Plantinum'), ('E', 'Emerald'), ('D', 'Diamond')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('BV', 'Best Value')], max_length=2),
        ),
    ]
