# Generated by Django 3.1.5 on 2022-01-12 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0036_auto_20220112_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Upload a file for the cover image of your product.', upload_to=''),
            preserve_default=False,
        ),
    ]
