# Generated by Django 3.1.5 on 2022-01-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0039_auto_20220115_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
