# Generated by Django 3.1.5 on 2022-01-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0041_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
