# Generated by Django 3.1.5 on 2022-01-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0043_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Website'},
        ),
    ]
