# Generated by Django 3.1.5 on 2022-01-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0050_auto_20220120_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
