# Generated by Django 3.2.11 on 2022-01-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0053_auto_20220122_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
