# Generated by Django 3.2.11 on 2022-01-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0055_auto_20220122_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
