# Generated by Django 3.2.11 on 2022-01-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0056_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile2',
            options={'verbose_name': 'Edit Profile', 'verbose_name_plural': 'Edit Profiles'},
        ),
    ]
