# Generated by Django 3.2.11 on 2022-02-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0058_auto_20220127_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile2',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
