# Generated by Django 3.2.11 on 2022-03-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0060_item_relateditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('G', 'Gold'), ('P', 'Platinum'), ('E', 'Emerald'), ('D', 'Diamond')], max_length=2),
        ),
    ]
