# Generated by Django 3.2.11 on 2022-06-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0065_supportmessage_api_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='api_time',
        ),
    ]
