# Generated by Django 3.2.11 on 2022-06-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0066_remove_supportmessage_api_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportchat',
            name='api_time',
        ),
    ]
