# Generated by Django 3.2.11 on 2022-06-15 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0067_remove_supportchat_api_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 22, 34, 12, 574179, tzinfo=utc)),
        ),
    ]
