# Generated by Django 3.2.11 on 2022-07-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0074_alter_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Upload a background image for the cover page.', upload_to='')),
            ],
        ),
    ]
