# Generated by Django 3.2.11 on 2022-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0075_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='relateditems',
            field=models.ManyToManyField(blank=True, null=True, related_name='_showcase_item_relateditems_+', to='showcase.Item'),
        ),
    ]
