# Generated by Django 3.2.11 on 2022-07-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0078_backgroundimage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundimage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(help_text='Upload a background image for the cover page.', upload_to=''),
        ),
    ]
