# Generated by Django 3.2.11 on 2022-07-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0079_auto_20220715_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a background image for the cover page.', upload_to='')),
            ],
            options={
                'verbose_name': 'Ecommerce Background Image',
                'verbose_name_plural': 'Ecommerce Background Images',
            },
        ),
    ]
