# Generated by Django 3.2.11 on 2022-08-11 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0081_alter_backgroundimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcasepost',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='backgroundimage',
            name='image',
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
