# Generated by Django 3.2.11 on 2022-10-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0085_chatbackgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'About Background Image',
                'verbose_name_plural': 'About Background Images',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Title 1',
                'verbose_name_plural': 'About Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Description 2',
                'verbose_name_plural': 'About Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Title 3',
                'verbose_name_plural': 'About Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Description 4',
                'verbose_name_plural': 'About Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Title 5',
                'verbose_name_plural': 'About Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Description 6',
                'verbose_name_plural': 'About Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Title 7',
                'verbose_name_plural': 'About Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='AboutTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Text Field Description 8',
                'verbose_name_plural': 'About Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImageBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundtitle', models.TextField(verbose_name='Background Title')),
                ('cover', models.ImageField(upload_to='images/')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('url', models.URLField(verbose_name='Page URL')),
                ('position', models.IntegerField(verbose_name='Positioning of Image')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Background Image Base',
                'verbose_name_plural': 'Background Image Base',
            },
        ),
        migrations.CreateModel(
            name='BaseCopyrightTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Base Text Field Copyright',
                'verbose_name_plural': 'Base Text Field Copyright',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Title 1',
                'verbose_name_plural': 'Billet Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Description 2',
                'verbose_name_plural': 'Billet Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Title 3',
                'verbose_name_plural': 'Billet Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Description 4',
                'verbose_name_plural': 'Billet Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Title 5',
                'verbose_name_plural': 'Billet Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Description 6',
                'verbose_name_plural': 'Billet Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Title 7',
                'verbose_name_plural': 'Billet Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='BilletTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Billet Text Field Description 8',
                'verbose_name_plural': 'Billet Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='BlogBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('cover', models.ImageField(upload_to='images/', verbose_name='Cover')),
            ],
            options={
                'verbose_name': 'Blog Background Image',
                'verbose_name_plural': 'Blog Background Images',
            },
        ),
        migrations.CreateModel(
            name='ContentBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Content Background Image',
                'verbose_name_plural': 'Content Background Images',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Content Text Field Title 1',
                'verbose_name_plural': 'Content Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Text Field Description 2',
                'verbose_name_plural': 'Content Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Text Field Title 3',
                'verbose_name_plural': 'Content Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Text Field Description 4',
                'verbose_name_plural': 'Content Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Text Field Title 5',
                'verbose_name_plural': 'Content Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Text Field Description 6',
                'verbose_name_plural': 'Content Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Text Field Title 7',
                'verbose_name_plural': 'Content Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='ContentTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Content Text Field Description 8',
                'verbose_name_plural': 'Content Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='ContributorBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Contributors Background Image',
                'verbose_name_plural': 'Contributors Background Images',
            },
        ),
        migrations.CreateModel(
            name='ConvertBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Convert Background Image',
                'verbose_name_plural': 'Convert Background Images',
            },
        ),
        migrations.CreateModel(
            name='DonateIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Donation Icon',
                'verbose_name_plural': 'Donation Icons',
            },
        ),
        migrations.CreateModel(
            name='DonorBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Donors Background Image',
                'verbose_name_plural': 'Donors Background Images',
            },
        ),
        migrations.CreateModel(
            name='EventBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Event Background Image',
                'verbose_name_plural': 'Event Background Images',
            },
        ),
        migrations.CreateModel(
            name='FaqBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'FAQ Background Image',
                'verbose_name_plural': 'FAQ Background Images',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 1',
                'verbose_name_plural': 'FAQ Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 10',
                'verbose_name_plural': 'FAQ Text Field Descriptions 10',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 11',
                'verbose_name_plural': 'FAQ Text Field Titles 11',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 12',
                'verbose_name_plural': 'FAQ Text Fields Descriptions 12',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 13',
                'verbose_name_plural': 'FAQ Text Field Titles 13',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 14',
                'verbose_name_plural': 'FAQ Text Field Descriptions 14',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 15',
                'verbose_name_plural': 'FAQ Text Field Titles 15',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 16',
                'verbose_name_plural': 'FAQ Text Field Descriptions 16',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 17',
                'verbose_name_plural': 'FAQ Text Field Titles 17',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 18',
                'verbose_name_plural': 'FAQ Text Field Descriptions 18',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 2',
                'verbose_name_plural': 'FAQ Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 3',
                'verbose_name_plural': 'FAQ Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 4',
                'verbose_name_plural': 'FAQ Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 5',
                'verbose_name_plural': 'FAQ Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 6',
                'verbose_name_plural': 'FAQ Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 7',
                'verbose_name_plural': 'FAQ Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Description 8',
                'verbose_name_plural': 'FAQ Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='FaqTextField9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Text Field Title 9',
                'verbose_name_plural': 'FAQ Text Field Titles 9',
            },
        ),
        migrations.CreateModel(
            name='FaviconBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicontitle', models.TextField(verbose_name='Favicon Title')),
                ('faviconcover', models.ImageField(upload_to='images/', verbose_name='Cover')),
                ('faviconpage', models.TextField(verbose_name='Page Name')),
                ('faviconurl', models.URLField(verbose_name='Page URL')),
                ('faviconlink', models.TextField(verbose_name='Favicon Link')),
                ('faviconsizes', models.TextField(help_text='example: 180x180', verbose_name='Favicon Sizes')),
                ('faviconrelationship', models.TextField(help_text='example: icon', verbose_name='Favicon Relationship')),
                ('favicontype', models.TextField(help_text='example: .ico', verbose_name='Favicon Type')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicons',
            },
        ),
        migrations.CreateModel(
            name='InformationBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Information Background Image',
                'verbose_name_plural': 'Information Background Images',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Title 1',
                'verbose_name_plural': 'Information Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Description 2',
                'verbose_name_plural': 'Information Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Title 3',
                'verbose_name_plural': 'Information Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Description 4',
                'verbose_name_plural': 'Information Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Title 5',
                'verbose_name_plural': 'Informations Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Description 6',
                'verbose_name_plural': 'Information Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Title 7',
                'verbose_name_plural': 'Information Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Description 8',
                'verbose_name_plural': 'Information Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='InformationTextField9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Text Field Description 9',
                'verbose_name_plural': 'Information Text Fields Descriptions 9',
            },
        ),
        migrations.CreateModel(
            name='MegaBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Mega Background Image',
                'verbose_name_plural': 'Mega Background Images',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Title 1',
                'verbose_name_plural': 'MegaCoins Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Description 2',
                'verbose_name_plural': 'MegaCoins Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Title 3',
                'verbose_name_plural': 'MegaCoins Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Description 4',
                'verbose_name_plural': 'MegaCoins Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Title 5',
                'verbose_name_plural': 'MegaCoins Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Description 6',
                'verbose_name_plural': 'MegaCoins Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Title 7',
                'verbose_name_plural': 'MegaCoins Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='MegaCoinsTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'MegaCoins Text Field Description 8',
                'verbose_name_plural': 'MegaCoins Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.TextField(blank=True, null=True)),
                ('row', models.IntegerField()),
                ('position', models.IntegerField()),
                ('opennew', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Open In New Tab?')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Navigational Bar Dropdown',
                'verbose_name_plural': 'Navigational Bar Dropdowns',
            },
        ),
        migrations.CreateModel(
            name='NavBarHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='This is a header.')),
                ('section', models.TextField(blank=True, help_text='ID Section of page.', max_length=200, null=True)),
                ('row', models.IntegerField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Navigational Bar Header',
                'verbose_name_plural': 'Navigational Bar Headers',
            },
        ),
        migrations.CreateModel(
            name='NewsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'News Background Image',
                'verbose_name_plural': 'News Background Images',
            },
        ),
        migrations.CreateModel(
            name='PartnerBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Partner Background Image',
                'verbose_name_plural': 'Partner Background Images',
            },
        ),
        migrations.CreateModel(
            name='Patreon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patreon_username', models.CharField(help_text='The patreon`s username goes here.', max_length=100, verbose_name='Patreon`s Username')),
                ('description', models.TextField(help_text='Description of Patreon`s patreonage.')),
                ('image', models.ImageField(help_text='The patreon`s avatar goes here.', upload_to='')),
            ],
            options={
                'verbose_name': 'Patreon',
                'verbose_name_plural': 'Patreons',
            },
        ),
        migrations.CreateModel(
            name='PatreonBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Patreon Background Image',
                'verbose_name_plural': 'Patreon Background Images',
            },
        ),
        migrations.CreateModel(
            name='PostBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Idea Background Image',
                'verbose_name_plural': 'Idea Background Images',
            },
        ),
        migrations.CreateModel(
            name='PosteBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Idea Background Image',
                'verbose_name_plural': 'Idea Background Images',
            },
        ),
        migrations.CreateModel(
            name='RuleBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Rule Background Image',
                'verbose_name_plural': 'Rule Background Images',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Title 1',
                'verbose_name_plural': 'Rules Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Description 10',
                'verbose_name_plural': 'Rules Text Field Descriptions 10',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Title 11',
                'verbose_name_plural': 'Rules Text Field Titles 11',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Description 12',
                'verbose_name_plural': 'Rules Text Field Descriptions 12',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Description 2',
                'verbose_name_plural': 'Rules Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Title 3',
                'verbose_name_plural': 'Rules Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Description 4',
                'verbose_name_plural': 'Rules Text Field Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Title 5',
                'verbose_name_plural': 'Rules Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Description 6',
                'verbose_name_plural': 'Rules Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Title 7',
                'verbose_name_plural': 'Rules Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Description 8',
                'verbose_name_plural': 'Rules Text Field Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='RuleTextField9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Rules Text Field Title 9',
                'verbose_name_plural': 'Rules Text Field Titles 9',
            },
        ),
        migrations.CreateModel(
            name='ShareBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Share Background Image',
                'verbose_name_plural': 'Share Background Images',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Showcase Background Image',
                'verbose_name_plural': 'Showcase Background Images',
            },
        ),
        migrations.CreateModel(
            name='StaffApplyBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Staff Application Background Image',
                'verbose_name_plural': 'Staff Application Background Images',
            },
        ),
        migrations.CreateModel(
            name='StaffBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Staff Background Image',
                'verbose_name_plural': 'Staff Background Images',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Staff Ranks Background Image',
                'verbose_name_plural': 'Staff Ranks Background Images',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 1',
                'verbose_name_plural': 'StaffRanks Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 10',
                'verbose_name_plural': 'StaffRanks Text Field Descriptions 10',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 11',
                'verbose_name_plural': 'StaffRanks Text Field Titles 11',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 12',
                'verbose_name_plural': 'StaffRanks Text Fields Descriptions 12',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 13',
                'verbose_name_plural': 'StaffRanks Text Field Titles 13',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 14',
                'verbose_name_plural': 'StaffRanks Text Field Descriptions 14',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 15',
                'verbose_name_plural': 'StaffRanks Text Field Titles 15',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 16',
                'verbose_name_plural': 'StaffRanks Text Field Descriptions 16',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 17',
                'verbose_name_plural': 'StaffRanks Text Field Titles 17',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 18',
                'verbose_name_plural': 'StaffRanks Text Field Descriptions 18',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 2',
                'verbose_name_plural': 'StaffRanks Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 3',
                'verbose_name_plural': 'StaffRanks Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 4',
                'verbose_name_plural': 'StaffRanks Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 5',
                'verbose_name_plural': 'StaffRanks Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 6',
                'verbose_name_plural': 'StaffRanks Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 7',
                'verbose_name_plural': 'StaffRanks Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Description 8',
                'verbose_name_plural': 'StaffRanks Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='StaffRanksTextField9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'StaffRanks Text Field Title 9',
                'verbose_name_plural': 'StaffRanks Text Field Titles 9',
            },
        ),
        migrations.CreateModel(
            name='SupportChatBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Support Chat Background Image',
                'verbose_name_plural': 'Support Chat Background Images',
            },
        ),
        migrations.CreateModel(
            name='TagBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Tag Background Image',
                'verbose_name_plural': 'Tag Background Images',
            },
        ),
        migrations.CreateModel(
            name='TextBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('url', models.URLField(verbose_name='Page URL')),
                ('header_or_textfield', models.BooleanField(choices=[(1, 'Header'), (0, 'Body')], default=1, verbose_name='Header or Body Text')),
                ('section', models.IntegerField(help_text='Section Number of Text', verbose_name='Text Section')),
                ('exists', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, help_text='Is this section taken?', verbose_name='Section Taken')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Text Base',
                'verbose_name_plural': 'Text Base',
            },
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Title 1',
                'verbose_name_plural': 'Text Field Titles 1',
            },
        ),
        migrations.CreateModel(
            name='TextField2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Description 2',
                'verbose_name_plural': 'Text Field Descriptions 2',
            },
        ),
        migrations.CreateModel(
            name='TextField3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Title 3',
                'verbose_name_plural': 'Text Field Titles 3',
            },
        ),
        migrations.CreateModel(
            name='TextField4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Description 4',
                'verbose_name_plural': 'Text Fields Descriptions 4',
            },
        ),
        migrations.CreateModel(
            name='TextField5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Title 5',
                'verbose_name_plural': 'Text Field Titles 5',
            },
        ),
        migrations.CreateModel(
            name='TextField6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Description 6',
                'verbose_name_plural': 'Text Field Descriptions 6',
            },
        ),
        migrations.CreateModel(
            name='TextField7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Title 7',
                'verbose_name_plural': 'Text Field Titles 7',
            },
        ),
        migrations.CreateModel(
            name='TextField8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text Field Description 8',
                'verbose_name_plural': 'Text Fields Descriptions 8',
            },
        ),
        migrations.CreateModel(
            name='Titled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtitle', models.TextField(verbose_name='Title')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('url', models.URLField(verbose_name='Page URL')),
                ('position', models.IntegerField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Page Title',
                'verbose_name_plural': 'Page Titles',
            },
        ),
        migrations.CreateModel(
            name='UserBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'User Background Image',
                'verbose_name_plural': 'Users Background Images',
            },
        ),
        migrations.CreateModel(
            name='VoteBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Vote Background Image',
                'verbose_name_plural': 'Vote Background Images',
            },
        ),
        migrations.CreateModel(
            name='WhyBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Why Background Image',
                'verbose_name_plural': 'Why Background Images',
            },
        ),
        migrations.AlterModelOptions(
            name='chatbackgroundimage',
            options={'verbose_name': 'Chat Background Image', 'verbose_name_plural': 'Chat Background Images'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Navigational Bar Header', 'verbose_name_plural': 'Navigational Bar Headers'},
        ),
        migrations.AlterModelOptions(
            name='showcasepost',
            options={'verbose_name': 'User Profile Idea', 'verbose_name_plural': 'User Profile Posts'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='full_name',
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='percentDollars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebackgroundimage',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='coupons',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Send me coupons'),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='news',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Keep me in the loop'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='username',
            field=models.TextField(help_text='Your username'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='meeting_attendance_check',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I can attend at least half of the staff meetings.'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='read_requirements',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I confirm that I have read all the staff requiernments and meet all of them.'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='overall_time_check',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have been in MC for at least 2 months'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='previous_role_time_check',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have been in MC for at least 1 month'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='strikes_check',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have no strikes on my account currently'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='role',
            field=models.TextField(help_text='What role are you applying for?', verbose_name='Roles'),
        ),
    ]
