# Generated by Django 4.1.2 on 2022-11-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0086_auto_20221025_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Account Background Image',
                'verbose_name_plural': 'Account Background Images',
            },
        ),
        migrations.CreateModel(
            name='AddonsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Addons Background Image',
                'verbose_name_plural': 'Addons Background Images',
            },
        ),
        migrations.CreateModel(
            name='CommitmentBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Commitment Background Image',
                'verbose_name_plural': 'Commitment Background Images',
            },
        ),
        migrations.CreateModel(
            name='ContactBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Contact Background Image',
                'verbose_name_plural': 'Contact Background Images',
            },
        ),
        migrations.CreateModel(
            name='CostBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Cost Background Image',
                'verbose_name_plural': 'Cost Background Images',
            },
        ),
        migrations.CreateModel(
            name='MantenienceBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Mantenience Background Image',
                'verbose_name_plural': 'Mantenience Background Images',
            },
        ),
        migrations.CreateModel(
            name='PerksBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Perks Background Image',
                'verbose_name_plural': 'Perks Background Images',
            },
        ),
        migrations.CreateModel(
            name='PriceBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Price Background Image',
                'verbose_name_plural': 'Price Background Images',
            },
        ),
        migrations.CreateModel(
            name='ServerBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Server Background Image',
                'verbose_name_plural': 'Server Background Images',
            },
        ),
        migrations.CreateModel(
            name='TiersBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Tiers Background Image',
                'verbose_name_plural': 'Tiers Background Images',
            },
        ),
        migrations.CreateModel(
            name='WebsiteBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Website Background Image',
                'verbose_name_plural': 'Website Background Images',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='password',
            field=models.CharField(default=1, help_text='Your password', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='relateditems',
            field=models.ManyToManyField(blank=True, to='showcase.item'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='username',
            field=models.CharField(help_text='Your username', max_length=200),
        ),
    ]
