# Generated by Django 4.1.2 on 2022-11-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0088_imagecarousel_alter_backgroundimagebase_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SettingsModel',
        ),
    ]
