# Generated by Django 4.1.2 on 2022-11-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0091_settings_delete_imagecarousel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Your name goes here.', max_length=100)),
                ('caption', models.TextField(help_text='Caption for the image.')),
                ('image', models.ImageField(help_text='Link a URL for your profile (scales to your picture`s dimensions.)', upload_to='')),
                ('position', models.IntegerField(help_text='Positioning of image.')),
                ('page', models.TextField(verbose_name='Page Name')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Image Carousel Idea',
                'verbose_name_plural': 'Image Carousel Posts',
            },
        ),
        migrations.CreateModel(
            name='LogoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Background Title')),
                ('cover', models.ImageField(upload_to='images/')),
                ('url', models.URLField(verbose_name='Page URL')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='SettingsBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Settings Background Image',
                'verbose_name_plural': 'Settings Background Images',
            },
        ),
        migrations.RenameModel(
            old_name='Settings',
            new_name='SettingsModel',
        ),
        migrations.AlterField(
            model_name='backgroundimagebase',
            name='position',
            field=models.IntegerField(verbose_name='Image Position'),
        ),
    ]
