# Generated by Django 4.1.2 on 2022-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0092_imagecarousel_logobase_settingsbackgroundimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logobase',
            name='url',
        ),
        migrations.AddField(
            model_name='logobase',
            name='page',
            field=models.TextField(default=1, verbose_name='Page Name'),
            preserve_default=False,
        ),
    ]
