# Generated by Django 4.1.2 on 2022-11-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0097_rename_cover_logobase_logocover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Order Background Image',
                'verbose_name_plural': 'Order Background Images',
            },
        ),
        migrations.CreateModel(
            name='ProductBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Product Background Image',
                'verbose_name_plural': 'Product Background Images',
            },
        ),
        migrations.AlterField(
            model_name='titled',
            name='page',
            field=models.TextField(blank=True, null=True, verbose_name='Page Name'),
        ),
    ]
