# Generated by Django 4.1.2 on 2022-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0105_alter_advertisementbase_advertisement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecarousel',
            old_name='image',
            new_name='carouselimage',
        ),
        migrations.RemoveField(
            model_name='imagecarousel',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='imagecarousel',
            name='title',
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='carouselcaption',
            field=models.TextField(default=1, help_text='Caption for the image.', verbose_name='caption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecarousel',
            name='carouseltitle',
            field=models.CharField(default=1, help_text='Title of the image.', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
