# Generated by Django 4.1.2 on 2022-11-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0107_remove_imagecarousel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecarousel',
            name='carouselimage',
            field=models.ImageField(help_text='Link a URL for your profile (scales to your picture`s dimensions.)', upload_to='', verbose_name='image'),
        ),
    ]
