# Generated by Django 4.1.2 on 2023-01-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0117_rename_blog_blogpost_newsfeed_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMailingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Recipient of your message.')),
                ('inquiry', models.CharField(help_text='Subject of your message.', max_length=100)),
                ('message', models.TextField(help_text='Your message goes here.')),
            ],
            options={
                'verbose_name': 'Business Mailing Message',
                'verbose_name_plural': 'Business Mailing Messages',
            },
        ),
    ]
